platform :ios, '10.0'

source 'https://github.com/Masabi/Podspecs.git'

target 'NavitiaSDKUI-Example' do
  use_frameworks!

  pod 'NavitiaSDKUI', :path => '../'

  target 'NavitiaSDKUI-ExampleTests' do
    inherit! :search_paths
    
    pod 'NavitiaSDKUI', :path => '../'
    # Pods for testing
  end

  target 'NavitiaSDKUI-ExampleUITests' do
    inherit! :search_paths
    
    pod 'NavitiaSDKUI', :path => '../'
    # Pods for testing
  end

end
