//
// HeatMap1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

open class HeatMap1: JSONEncodable, Mappable {

    public var links: [LinkSchema]?
    public var warnings: [BetaEndpoints]?
    public var heatMaps: [HeatMap]?
    public var feedPublishers: [FeedPublisher]?
    public var context: Context?
    public var error: ModelError?

    public init() {}
    required public init?(map: Map) {

    }


    public func mapping(map: Map) {
        links <- map["links"]
        warnings <- map["warnings"]
        heatMaps <- map["heat_maps"]
        feedPublishers <- map["feed_publishers"]
        context <- map["context"]
        error <- map["error"]
    }

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["links"] = self.links?.encodeToJSON()
        nillableDictionary["warnings"] = self.warnings?.encodeToJSON()
        nillableDictionary["heat_maps"] = self.heatMaps?.encodeToJSON()
        nillableDictionary["feed_publishers"] = self.feedPublishers?.encodeToJSON()
        nillableDictionary["context"] = self.context?.encodeToJSON()
        nillableDictionary["error"] = self.error?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
