//
//  ListPlacesModels.swift
//  Pods
//
//  Created by Flavien Sicard on 30/01/2019.
//  Copyright (c) 2019 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListPlaces
{
  // MARK: Use cases
  
  enum FetchPlaces
  {
    struct Request
    {
        var q: String
        var coord: (lat: Double, lon: Double)?
    }
    struct Response
    {
        var places: Places?
    }
    struct ViewModel
    {
        enum ModelType {
            case stopArea
            case address
            case poi
        }
        
        struct Place {
            var name: String
            var id: String
        }
        
        struct Section {
            var type: ModelType
            var name: String
            var places: [Place]
        }
        
        var sections: [Section]
    }
  }
}
