//
// DisruptionsApi.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

open class CoverageLonLatDisruptionsRequestBuilder: NSObject {
    let currentApi: DisruptionsApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var lat:Double? = nil
    var lon:Double? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var externalCode:String? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var filter:String? = nil
    var tags:[String]? = nil
    var originalId:String? = nil
    var debugURL: String? = nil

    public init(currentApi: DisruptionsApi) {
        self.currentApi = currentApi
    }

    open func withLat(_ lat: Double?) -> CoverageLonLatDisruptionsRequestBuilder {
        self.lat = lat
        
        return self
    }
    open func withLon(_ lon: Double?) -> CoverageLonLatDisruptionsRequestBuilder {
        self.lon = lon
        
        return self
    }
    open func withStartPage(_ startPage: Int32?) -> CoverageLonLatDisruptionsRequestBuilder {
        self.startPage = startPage
        
        return self
    }
    open func withCount(_ count: Int32?) -> CoverageLonLatDisruptionsRequestBuilder {
        self.count = count
        
        return self
    }
    open func withDepth(_ depth: Int32?) -> CoverageLonLatDisruptionsRequestBuilder {
        self.depth = depth
        
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]?) -> CoverageLonLatDisruptionsRequestBuilder {
        self.forbiddenId = forbiddenId
        
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]?) -> CoverageLonLatDisruptionsRequestBuilder {
        self.forbiddenUris = forbiddenUris
        
        return self
    }
    open func withExternalCode(_ externalCode: String?) -> CoverageLonLatDisruptionsRequestBuilder {
        self.externalCode = externalCode
        
        return self
    }
    open func withHeadsign(_ headsign: String?) -> CoverageLonLatDisruptionsRequestBuilder {
        self.headsign = headsign
        
        return self
    }
    open func withShowCodes(_ showCodes: Bool?) -> CoverageLonLatDisruptionsRequestBuilder {
        self.showCodes = showCodes
        
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel?) -> CoverageLonLatDisruptionsRequestBuilder {
        self.odtLevel = odtLevel

        return self
    }
    open func withDistance(_ distance: Int32?) -> CoverageLonLatDisruptionsRequestBuilder {
        self.distance = distance
        
        return self
    }
    open func withSince(_ since: Date?) -> CoverageLonLatDisruptionsRequestBuilder {
        self.since = since
        
        return self
    }
    open func withUntil(_ until: Date?) -> CoverageLonLatDisruptionsRequestBuilder {
        self.until = until
        
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool?) -> CoverageLonLatDisruptionsRequestBuilder {
        self.disableGeojson = disableGeojson
        
        return self
    }
    open func withFilter(_ filter: String?) -> CoverageLonLatDisruptionsRequestBuilder {
        self.filter = filter
        
        return self
    }
    open func withTags(_ tags: [String]?) -> CoverageLonLatDisruptionsRequestBuilder {
        self.tags = tags
        
        return self
    }
    open func withOriginalId(_ originalId: String?) -> CoverageLonLatDisruptionsRequestBuilder {
        self.originalId = originalId
        
        return self
    }



    open func withDebugURL(_ debugURL: String?) -> CoverageLonLatDisruptionsRequestBuilder {
        self.debugURL = debugURL
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{lon};{lat}/disruptions"

        if let lat = lat {
            let latPreEscape: String = "\(lat)"
            let latPostEscape: String = latPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lat}", with: latPostEscape, options: .literal, range: nil)
        }

        if let lon = lon {
            let lonPreEscape: String = "\(lon)"
            let lonPostEscape: String = lonPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lon}", with: lonPostEscape, options: .literal, range: nil)
        }

        let URLString = String(format: "%@%@", NavitiaSDKAPI.basePath, path)
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "filter": self.filter, 
            "tags[]": self.tags, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (debugURL ?? url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: Disruptions?,_ error: Error?) -> Void)) {
        if (self.lat == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
        }
        if (self.lon == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<Disruptions>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.lat == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
    }
    if (self.lon == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageLonLatDisruptionsIdRequestBuilder: NSObject {
    let currentApi: DisruptionsApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var lat:Double? = nil
    var lon:Double? = nil
    var id:String? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var externalCode:String? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var tags:[String]? = nil
    var originalId:String? = nil
    var debugURL: String? = nil

    public init(currentApi: DisruptionsApi) {
        self.currentApi = currentApi
    }

    open func withLat(_ lat: Double?) -> CoverageLonLatDisruptionsIdRequestBuilder {
        self.lat = lat
        
        return self
    }
    open func withLon(_ lon: Double?) -> CoverageLonLatDisruptionsIdRequestBuilder {
        self.lon = lon
        
        return self
    }
    open func withId(_ id: String?) -> CoverageLonLatDisruptionsIdRequestBuilder {
        self.id = id
        
        return self
    }
    open func withStartPage(_ startPage: Int32?) -> CoverageLonLatDisruptionsIdRequestBuilder {
        self.startPage = startPage
        
        return self
    }
    open func withCount(_ count: Int32?) -> CoverageLonLatDisruptionsIdRequestBuilder {
        self.count = count
        
        return self
    }
    open func withDepth(_ depth: Int32?) -> CoverageLonLatDisruptionsIdRequestBuilder {
        self.depth = depth
        
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]?) -> CoverageLonLatDisruptionsIdRequestBuilder {
        self.forbiddenId = forbiddenId
        
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]?) -> CoverageLonLatDisruptionsIdRequestBuilder {
        self.forbiddenUris = forbiddenUris
        
        return self
    }
    open func withExternalCode(_ externalCode: String?) -> CoverageLonLatDisruptionsIdRequestBuilder {
        self.externalCode = externalCode
        
        return self
    }
    open func withHeadsign(_ headsign: String?) -> CoverageLonLatDisruptionsIdRequestBuilder {
        self.headsign = headsign
        
        return self
    }
    open func withShowCodes(_ showCodes: Bool?) -> CoverageLonLatDisruptionsIdRequestBuilder {
        self.showCodes = showCodes
        
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel?) -> CoverageLonLatDisruptionsIdRequestBuilder {
        self.odtLevel = odtLevel

        return self
    }
    open func withDistance(_ distance: Int32?) -> CoverageLonLatDisruptionsIdRequestBuilder {
        self.distance = distance
        
        return self
    }
    open func withSince(_ since: Date?) -> CoverageLonLatDisruptionsIdRequestBuilder {
        self.since = since
        
        return self
    }
    open func withUntil(_ until: Date?) -> CoverageLonLatDisruptionsIdRequestBuilder {
        self.until = until
        
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool?) -> CoverageLonLatDisruptionsIdRequestBuilder {
        self.disableGeojson = disableGeojson
        
        return self
    }
    open func withTags(_ tags: [String]?) -> CoverageLonLatDisruptionsIdRequestBuilder {
        self.tags = tags
        
        return self
    }
    open func withOriginalId(_ originalId: String?) -> CoverageLonLatDisruptionsIdRequestBuilder {
        self.originalId = originalId
        
        return self
    }



    open func withDebugURL(_ debugURL: String?) -> CoverageLonLatDisruptionsIdRequestBuilder {
        self.debugURL = debugURL
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{lon};{lat}/disruptions/{id}"

        if let lat = lat {
            let latPreEscape: String = "\(lat)"
            let latPostEscape: String = latPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lat}", with: latPostEscape, options: .literal, range: nil)
        }

        if let lon = lon {
            let lonPreEscape: String = "\(lon)"
            let lonPostEscape: String = lonPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lon}", with: lonPostEscape, options: .literal, range: nil)
        }

        if let id = id {
            let idPreEscape: String = "\(id)"
            let idPostEscape: String = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        }

        let URLString = String(format: "%@%@", NavitiaSDKAPI.basePath, path)
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "tags[]": self.tags, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (debugURL ?? url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: Disruptions?,_ error: Error?) -> Void)) {
        if (self.lat == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
        }
        if (self.lon == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
        }
        if (self.id == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<Disruptions>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.lat == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
    }
    if (self.lon == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
    }
    if (self.id == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageLonLatUriDisruptionsRequestBuilder: NSObject {
    let currentApi: DisruptionsApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var lat:Double? = nil
    var lon:Double? = nil
    var uri:String? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var externalCode:String? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var filter:String? = nil
    var tags:[String]? = nil
    var originalId:String? = nil
    var debugURL: String? = nil

    public init(currentApi: DisruptionsApi) {
        self.currentApi = currentApi
    }

    open func withLat(_ lat: Double?) -> CoverageLonLatUriDisruptionsRequestBuilder {
        self.lat = lat
        
        return self
    }
    open func withLon(_ lon: Double?) -> CoverageLonLatUriDisruptionsRequestBuilder {
        self.lon = lon
        
        return self
    }
    open func withUri(_ uri: String?) -> CoverageLonLatUriDisruptionsRequestBuilder {
        self.uri = uri
        
        return self
    }
    open func withStartPage(_ startPage: Int32?) -> CoverageLonLatUriDisruptionsRequestBuilder {
        self.startPage = startPage
        
        return self
    }
    open func withCount(_ count: Int32?) -> CoverageLonLatUriDisruptionsRequestBuilder {
        self.count = count
        
        return self
    }
    open func withDepth(_ depth: Int32?) -> CoverageLonLatUriDisruptionsRequestBuilder {
        self.depth = depth
        
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]?) -> CoverageLonLatUriDisruptionsRequestBuilder {
        self.forbiddenId = forbiddenId
        
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]?) -> CoverageLonLatUriDisruptionsRequestBuilder {
        self.forbiddenUris = forbiddenUris
        
        return self
    }
    open func withExternalCode(_ externalCode: String?) -> CoverageLonLatUriDisruptionsRequestBuilder {
        self.externalCode = externalCode
        
        return self
    }
    open func withHeadsign(_ headsign: String?) -> CoverageLonLatUriDisruptionsRequestBuilder {
        self.headsign = headsign
        
        return self
    }
    open func withShowCodes(_ showCodes: Bool?) -> CoverageLonLatUriDisruptionsRequestBuilder {
        self.showCodes = showCodes
        
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel?) -> CoverageLonLatUriDisruptionsRequestBuilder {
        self.odtLevel = odtLevel

        return self
    }
    open func withDistance(_ distance: Int32?) -> CoverageLonLatUriDisruptionsRequestBuilder {
        self.distance = distance
        
        return self
    }
    open func withSince(_ since: Date?) -> CoverageLonLatUriDisruptionsRequestBuilder {
        self.since = since
        
        return self
    }
    open func withUntil(_ until: Date?) -> CoverageLonLatUriDisruptionsRequestBuilder {
        self.until = until
        
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool?) -> CoverageLonLatUriDisruptionsRequestBuilder {
        self.disableGeojson = disableGeojson
        
        return self
    }
    open func withFilter(_ filter: String?) -> CoverageLonLatUriDisruptionsRequestBuilder {
        self.filter = filter
        
        return self
    }
    open func withTags(_ tags: [String]?) -> CoverageLonLatUriDisruptionsRequestBuilder {
        self.tags = tags
        
        return self
    }
    open func withOriginalId(_ originalId: String?) -> CoverageLonLatUriDisruptionsRequestBuilder {
        self.originalId = originalId
        
        return self
    }



    open func withDebugURL(_ debugURL: String?) -> CoverageLonLatUriDisruptionsRequestBuilder {
        self.debugURL = debugURL
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{lon};{lat}/{uri}/disruptions"

        if let lat = lat {
            let latPreEscape: String = "\(lat)"
            let latPostEscape: String = latPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lat}", with: latPostEscape, options: .literal, range: nil)
        }

        if let lon = lon {
            let lonPreEscape: String = "\(lon)"
            let lonPostEscape: String = lonPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lon}", with: lonPostEscape, options: .literal, range: nil)
        }

        if let uri = uri {
            let uriPreEscape: String = "\(uri)"
            let uriPostEscape: String = uriPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{uri}", with: uriPostEscape, options: .literal, range: nil)
        }

        let URLString = String(format: "%@%@", NavitiaSDKAPI.basePath, path)
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "filter": self.filter, 
            "tags[]": self.tags, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (debugURL ?? url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: Disruptions?,_ error: Error?) -> Void)) {
        if (self.lat == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
        }
        if (self.lon == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
        }
        if (self.uri == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<Disruptions>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.lat == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
    }
    if (self.lon == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
    }
    if (self.uri == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageLonLatUriDisruptionsIdRequestBuilder: NSObject {
    let currentApi: DisruptionsApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var lat:Double? = nil
    var lon:Double? = nil
    var uri:String? = nil
    var id:String? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var externalCode:String? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var tags:[String]? = nil
    var originalId:String? = nil
    var debugURL: String? = nil

    public init(currentApi: DisruptionsApi) {
        self.currentApi = currentApi
    }

    open func withLat(_ lat: Double?) -> CoverageLonLatUriDisruptionsIdRequestBuilder {
        self.lat = lat
        
        return self
    }
    open func withLon(_ lon: Double?) -> CoverageLonLatUriDisruptionsIdRequestBuilder {
        self.lon = lon
        
        return self
    }
    open func withUri(_ uri: String?) -> CoverageLonLatUriDisruptionsIdRequestBuilder {
        self.uri = uri
        
        return self
    }
    open func withId(_ id: String?) -> CoverageLonLatUriDisruptionsIdRequestBuilder {
        self.id = id
        
        return self
    }
    open func withStartPage(_ startPage: Int32?) -> CoverageLonLatUriDisruptionsIdRequestBuilder {
        self.startPage = startPage
        
        return self
    }
    open func withCount(_ count: Int32?) -> CoverageLonLatUriDisruptionsIdRequestBuilder {
        self.count = count
        
        return self
    }
    open func withDepth(_ depth: Int32?) -> CoverageLonLatUriDisruptionsIdRequestBuilder {
        self.depth = depth
        
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]?) -> CoverageLonLatUriDisruptionsIdRequestBuilder {
        self.forbiddenId = forbiddenId
        
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]?) -> CoverageLonLatUriDisruptionsIdRequestBuilder {
        self.forbiddenUris = forbiddenUris
        
        return self
    }
    open func withExternalCode(_ externalCode: String?) -> CoverageLonLatUriDisruptionsIdRequestBuilder {
        self.externalCode = externalCode
        
        return self
    }
    open func withHeadsign(_ headsign: String?) -> CoverageLonLatUriDisruptionsIdRequestBuilder {
        self.headsign = headsign
        
        return self
    }
    open func withShowCodes(_ showCodes: Bool?) -> CoverageLonLatUriDisruptionsIdRequestBuilder {
        self.showCodes = showCodes
        
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel?) -> CoverageLonLatUriDisruptionsIdRequestBuilder {
        self.odtLevel = odtLevel

        return self
    }
    open func withDistance(_ distance: Int32?) -> CoverageLonLatUriDisruptionsIdRequestBuilder {
        self.distance = distance
        
        return self
    }
    open func withSince(_ since: Date?) -> CoverageLonLatUriDisruptionsIdRequestBuilder {
        self.since = since
        
        return self
    }
    open func withUntil(_ until: Date?) -> CoverageLonLatUriDisruptionsIdRequestBuilder {
        self.until = until
        
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool?) -> CoverageLonLatUriDisruptionsIdRequestBuilder {
        self.disableGeojson = disableGeojson
        
        return self
    }
    open func withTags(_ tags: [String]?) -> CoverageLonLatUriDisruptionsIdRequestBuilder {
        self.tags = tags
        
        return self
    }
    open func withOriginalId(_ originalId: String?) -> CoverageLonLatUriDisruptionsIdRequestBuilder {
        self.originalId = originalId
        
        return self
    }



    open func withDebugURL(_ debugURL: String?) -> CoverageLonLatUriDisruptionsIdRequestBuilder {
        self.debugURL = debugURL
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{lon};{lat}/{uri}/disruptions/{id}"

        if let lat = lat {
            let latPreEscape: String = "\(lat)"
            let latPostEscape: String = latPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lat}", with: latPostEscape, options: .literal, range: nil)
        }

        if let lon = lon {
            let lonPreEscape: String = "\(lon)"
            let lonPostEscape: String = lonPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lon}", with: lonPostEscape, options: .literal, range: nil)
        }

        if let uri = uri {
            let uriPreEscape: String = "\(uri)"
            let uriPostEscape: String = uriPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{uri}", with: uriPostEscape, options: .literal, range: nil)
        }

        if let id = id {
            let idPreEscape: String = "\(id)"
            let idPostEscape: String = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        }

        let URLString = String(format: "%@%@", NavitiaSDKAPI.basePath, path)
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "tags[]": self.tags, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (debugURL ?? url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: Disruptions?,_ error: Error?) -> Void)) {
        if (self.lat == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
        }
        if (self.lon == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
        }
        if (self.uri == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
        }
        if (self.id == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<Disruptions>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.lat == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
    }
    if (self.lon == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
    }
    if (self.uri == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
    }
    if (self.id == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageRegionDisruptionsRequestBuilder: NSObject {
    let currentApi: DisruptionsApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var region:String? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var externalCode:String? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var filter:String? = nil
    var tags:[String]? = nil
    var originalId:String? = nil
    var debugURL: String? = nil

    public init(currentApi: DisruptionsApi) {
        self.currentApi = currentApi
    }

    open func withRegion(_ region: String?) -> CoverageRegionDisruptionsRequestBuilder {
        self.region = region
        
        return self
    }
    open func withStartPage(_ startPage: Int32?) -> CoverageRegionDisruptionsRequestBuilder {
        self.startPage = startPage
        
        return self
    }
    open func withCount(_ count: Int32?) -> CoverageRegionDisruptionsRequestBuilder {
        self.count = count
        
        return self
    }
    open func withDepth(_ depth: Int32?) -> CoverageRegionDisruptionsRequestBuilder {
        self.depth = depth
        
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]?) -> CoverageRegionDisruptionsRequestBuilder {
        self.forbiddenId = forbiddenId
        
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]?) -> CoverageRegionDisruptionsRequestBuilder {
        self.forbiddenUris = forbiddenUris
        
        return self
    }
    open func withExternalCode(_ externalCode: String?) -> CoverageRegionDisruptionsRequestBuilder {
        self.externalCode = externalCode
        
        return self
    }
    open func withHeadsign(_ headsign: String?) -> CoverageRegionDisruptionsRequestBuilder {
        self.headsign = headsign
        
        return self
    }
    open func withShowCodes(_ showCodes: Bool?) -> CoverageRegionDisruptionsRequestBuilder {
        self.showCodes = showCodes
        
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel?) -> CoverageRegionDisruptionsRequestBuilder {
        self.odtLevel = odtLevel

        return self
    }
    open func withDistance(_ distance: Int32?) -> CoverageRegionDisruptionsRequestBuilder {
        self.distance = distance
        
        return self
    }
    open func withSince(_ since: Date?) -> CoverageRegionDisruptionsRequestBuilder {
        self.since = since
        
        return self
    }
    open func withUntil(_ until: Date?) -> CoverageRegionDisruptionsRequestBuilder {
        self.until = until
        
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool?) -> CoverageRegionDisruptionsRequestBuilder {
        self.disableGeojson = disableGeojson
        
        return self
    }
    open func withFilter(_ filter: String?) -> CoverageRegionDisruptionsRequestBuilder {
        self.filter = filter
        
        return self
    }
    open func withTags(_ tags: [String]?) -> CoverageRegionDisruptionsRequestBuilder {
        self.tags = tags
        
        return self
    }
    open func withOriginalId(_ originalId: String?) -> CoverageRegionDisruptionsRequestBuilder {
        self.originalId = originalId
        
        return self
    }



    open func withDebugURL(_ debugURL: String?) -> CoverageRegionDisruptionsRequestBuilder {
        self.debugURL = debugURL
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{region}/disruptions"

        if let region = region {
            let regionPreEscape: String = "\(region)"
            let regionPostEscape: String = regionPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{region}", with: regionPostEscape, options: .literal, range: nil)
        }

        let URLString = String(format: "%@%@", NavitiaSDKAPI.basePath, path)
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "filter": self.filter, 
            "tags[]": self.tags, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (debugURL ?? url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: Disruptions?,_ error: Error?) -> Void)) {
        if (self.region == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<Disruptions>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.region == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageRegionDisruptionsIdRequestBuilder: NSObject {
    let currentApi: DisruptionsApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var region:String? = nil
    var id:String? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var externalCode:String? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var tags:[String]? = nil
    var originalId:String? = nil
    var debugURL: String? = nil

    public init(currentApi: DisruptionsApi) {
        self.currentApi = currentApi
    }

    open func withRegion(_ region: String?) -> CoverageRegionDisruptionsIdRequestBuilder {
        self.region = region
        
        return self
    }
    open func withId(_ id: String?) -> CoverageRegionDisruptionsIdRequestBuilder {
        self.id = id
        
        return self
    }
    open func withStartPage(_ startPage: Int32?) -> CoverageRegionDisruptionsIdRequestBuilder {
        self.startPage = startPage
        
        return self
    }
    open func withCount(_ count: Int32?) -> CoverageRegionDisruptionsIdRequestBuilder {
        self.count = count
        
        return self
    }
    open func withDepth(_ depth: Int32?) -> CoverageRegionDisruptionsIdRequestBuilder {
        self.depth = depth
        
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]?) -> CoverageRegionDisruptionsIdRequestBuilder {
        self.forbiddenId = forbiddenId
        
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]?) -> CoverageRegionDisruptionsIdRequestBuilder {
        self.forbiddenUris = forbiddenUris
        
        return self
    }
    open func withExternalCode(_ externalCode: String?) -> CoverageRegionDisruptionsIdRequestBuilder {
        self.externalCode = externalCode
        
        return self
    }
    open func withHeadsign(_ headsign: String?) -> CoverageRegionDisruptionsIdRequestBuilder {
        self.headsign = headsign
        
        return self
    }
    open func withShowCodes(_ showCodes: Bool?) -> CoverageRegionDisruptionsIdRequestBuilder {
        self.showCodes = showCodes
        
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel?) -> CoverageRegionDisruptionsIdRequestBuilder {
        self.odtLevel = odtLevel

        return self
    }
    open func withDistance(_ distance: Int32?) -> CoverageRegionDisruptionsIdRequestBuilder {
        self.distance = distance
        
        return self
    }
    open func withSince(_ since: Date?) -> CoverageRegionDisruptionsIdRequestBuilder {
        self.since = since
        
        return self
    }
    open func withUntil(_ until: Date?) -> CoverageRegionDisruptionsIdRequestBuilder {
        self.until = until
        
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool?) -> CoverageRegionDisruptionsIdRequestBuilder {
        self.disableGeojson = disableGeojson
        
        return self
    }
    open func withTags(_ tags: [String]?) -> CoverageRegionDisruptionsIdRequestBuilder {
        self.tags = tags
        
        return self
    }
    open func withOriginalId(_ originalId: String?) -> CoverageRegionDisruptionsIdRequestBuilder {
        self.originalId = originalId
        
        return self
    }



    open func withDebugURL(_ debugURL: String?) -> CoverageRegionDisruptionsIdRequestBuilder {
        self.debugURL = debugURL
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{region}/disruptions/{id}"

        if let region = region {
            let regionPreEscape: String = "\(region)"
            let regionPostEscape: String = regionPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{region}", with: regionPostEscape, options: .literal, range: nil)
        }

        if let id = id {
            let idPreEscape: String = "\(id)"
            let idPostEscape: String = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        }

        let URLString = String(format: "%@%@", NavitiaSDKAPI.basePath, path)
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "tags[]": self.tags, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (debugURL ?? url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: Disruptions?,_ error: Error?) -> Void)) {
        if (self.region == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
        }
        if (self.id == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<Disruptions>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.region == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
    }
    if (self.id == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageRegionUriDisruptionsRequestBuilder: NSObject {
    let currentApi: DisruptionsApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var region:String? = nil
    var uri:String? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var externalCode:String? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var filter:String? = nil
    var tags:[String]? = nil
    var originalId:String? = nil
    var debugURL: String? = nil

    public init(currentApi: DisruptionsApi) {
        self.currentApi = currentApi
    }

    open func withRegion(_ region: String?) -> CoverageRegionUriDisruptionsRequestBuilder {
        self.region = region
        
        return self
    }
    open func withUri(_ uri: String?) -> CoverageRegionUriDisruptionsRequestBuilder {
        self.uri = uri
        
        return self
    }
    open func withStartPage(_ startPage: Int32?) -> CoverageRegionUriDisruptionsRequestBuilder {
        self.startPage = startPage
        
        return self
    }
    open func withCount(_ count: Int32?) -> CoverageRegionUriDisruptionsRequestBuilder {
        self.count = count
        
        return self
    }
    open func withDepth(_ depth: Int32?) -> CoverageRegionUriDisruptionsRequestBuilder {
        self.depth = depth
        
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]?) -> CoverageRegionUriDisruptionsRequestBuilder {
        self.forbiddenId = forbiddenId
        
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]?) -> CoverageRegionUriDisruptionsRequestBuilder {
        self.forbiddenUris = forbiddenUris
        
        return self
    }
    open func withExternalCode(_ externalCode: String?) -> CoverageRegionUriDisruptionsRequestBuilder {
        self.externalCode = externalCode
        
        return self
    }
    open func withHeadsign(_ headsign: String?) -> CoverageRegionUriDisruptionsRequestBuilder {
        self.headsign = headsign
        
        return self
    }
    open func withShowCodes(_ showCodes: Bool?) -> CoverageRegionUriDisruptionsRequestBuilder {
        self.showCodes = showCodes
        
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel?) -> CoverageRegionUriDisruptionsRequestBuilder {
        self.odtLevel = odtLevel

        return self
    }
    open func withDistance(_ distance: Int32?) -> CoverageRegionUriDisruptionsRequestBuilder {
        self.distance = distance
        
        return self
    }
    open func withSince(_ since: Date?) -> CoverageRegionUriDisruptionsRequestBuilder {
        self.since = since
        
        return self
    }
    open func withUntil(_ until: Date?) -> CoverageRegionUriDisruptionsRequestBuilder {
        self.until = until
        
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool?) -> CoverageRegionUriDisruptionsRequestBuilder {
        self.disableGeojson = disableGeojson
        
        return self
    }
    open func withFilter(_ filter: String?) -> CoverageRegionUriDisruptionsRequestBuilder {
        self.filter = filter
        
        return self
    }
    open func withTags(_ tags: [String]?) -> CoverageRegionUriDisruptionsRequestBuilder {
        self.tags = tags
        
        return self
    }
    open func withOriginalId(_ originalId: String?) -> CoverageRegionUriDisruptionsRequestBuilder {
        self.originalId = originalId
        
        return self
    }



    open func withDebugURL(_ debugURL: String?) -> CoverageRegionUriDisruptionsRequestBuilder {
        self.debugURL = debugURL
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{region}/{uri}/disruptions"

        if let region = region {
            let regionPreEscape: String = "\(region)"
            let regionPostEscape: String = regionPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{region}", with: regionPostEscape, options: .literal, range: nil)
        }

        if let uri = uri {
            let uriPreEscape: String = "\(uri)"
            let uriPostEscape: String = uriPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{uri}", with: uriPostEscape, options: .literal, range: nil)
        }

        let URLString = String(format: "%@%@", NavitiaSDKAPI.basePath, path)
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "filter": self.filter, 
            "tags[]": self.tags, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (debugURL ?? url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: Disruptions?,_ error: Error?) -> Void)) {
        if (self.region == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
        }
        if (self.uri == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<Disruptions>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.region == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
    }
    if (self.uri == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageRegionUriDisruptionsIdRequestBuilder: NSObject {
    let currentApi: DisruptionsApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var region:String? = nil
    var uri:String? = nil
    var id:String? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var externalCode:String? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var tags:[String]? = nil
    var originalId:String? = nil
    var debugURL: String? = nil

    public init(currentApi: DisruptionsApi) {
        self.currentApi = currentApi
    }

    open func withRegion(_ region: String?) -> CoverageRegionUriDisruptionsIdRequestBuilder {
        self.region = region
        
        return self
    }
    open func withUri(_ uri: String?) -> CoverageRegionUriDisruptionsIdRequestBuilder {
        self.uri = uri
        
        return self
    }
    open func withId(_ id: String?) -> CoverageRegionUriDisruptionsIdRequestBuilder {
        self.id = id
        
        return self
    }
    open func withStartPage(_ startPage: Int32?) -> CoverageRegionUriDisruptionsIdRequestBuilder {
        self.startPage = startPage
        
        return self
    }
    open func withCount(_ count: Int32?) -> CoverageRegionUriDisruptionsIdRequestBuilder {
        self.count = count
        
        return self
    }
    open func withDepth(_ depth: Int32?) -> CoverageRegionUriDisruptionsIdRequestBuilder {
        self.depth = depth
        
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]?) -> CoverageRegionUriDisruptionsIdRequestBuilder {
        self.forbiddenId = forbiddenId
        
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]?) -> CoverageRegionUriDisruptionsIdRequestBuilder {
        self.forbiddenUris = forbiddenUris
        
        return self
    }
    open func withExternalCode(_ externalCode: String?) -> CoverageRegionUriDisruptionsIdRequestBuilder {
        self.externalCode = externalCode
        
        return self
    }
    open func withHeadsign(_ headsign: String?) -> CoverageRegionUriDisruptionsIdRequestBuilder {
        self.headsign = headsign
        
        return self
    }
    open func withShowCodes(_ showCodes: Bool?) -> CoverageRegionUriDisruptionsIdRequestBuilder {
        self.showCodes = showCodes
        
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel?) -> CoverageRegionUriDisruptionsIdRequestBuilder {
        self.odtLevel = odtLevel

        return self
    }
    open func withDistance(_ distance: Int32?) -> CoverageRegionUriDisruptionsIdRequestBuilder {
        self.distance = distance
        
        return self
    }
    open func withSince(_ since: Date?) -> CoverageRegionUriDisruptionsIdRequestBuilder {
        self.since = since
        
        return self
    }
    open func withUntil(_ until: Date?) -> CoverageRegionUriDisruptionsIdRequestBuilder {
        self.until = until
        
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool?) -> CoverageRegionUriDisruptionsIdRequestBuilder {
        self.disableGeojson = disableGeojson
        
        return self
    }
    open func withTags(_ tags: [String]?) -> CoverageRegionUriDisruptionsIdRequestBuilder {
        self.tags = tags
        
        return self
    }
    open func withOriginalId(_ originalId: String?) -> CoverageRegionUriDisruptionsIdRequestBuilder {
        self.originalId = originalId
        
        return self
    }



    open func withDebugURL(_ debugURL: String?) -> CoverageRegionUriDisruptionsIdRequestBuilder {
        self.debugURL = debugURL
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{region}/{uri}/disruptions/{id}"

        if let region = region {
            let regionPreEscape: String = "\(region)"
            let regionPostEscape: String = regionPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{region}", with: regionPostEscape, options: .literal, range: nil)
        }

        if let uri = uri {
            let uriPreEscape: String = "\(uri)"
            let uriPostEscape: String = uriPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{uri}", with: uriPostEscape, options: .literal, range: nil)
        }

        if let id = id {
            let idPreEscape: String = "\(id)"
            let idPostEscape: String = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        }

        let URLString = String(format: "%@%@", NavitiaSDKAPI.basePath, path)
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "tags[]": self.tags, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (debugURL ?? url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: Disruptions?,_ error: Error?) -> Void)) {
        if (self.region == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
        }
        if (self.uri == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
        }
        if (self.id == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<Disruptions>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.region == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
    }
    if (self.uri == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
    }
    if (self.id == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}



open class DisruptionsApi: APIBase {
    let token: String

    public init(token: String) {
        self.token = token
    }

    public func newCoverageLonLatDisruptionsRequestBuilder() -> CoverageLonLatDisruptionsRequestBuilder {
        return CoverageLonLatDisruptionsRequestBuilder(currentApi: self)
    }
    public func newCoverageLonLatDisruptionsIdRequestBuilder() -> CoverageLonLatDisruptionsIdRequestBuilder {
        return CoverageLonLatDisruptionsIdRequestBuilder(currentApi: self)
    }
    public func newCoverageLonLatUriDisruptionsRequestBuilder() -> CoverageLonLatUriDisruptionsRequestBuilder {
        return CoverageLonLatUriDisruptionsRequestBuilder(currentApi: self)
    }
    public func newCoverageLonLatUriDisruptionsIdRequestBuilder() -> CoverageLonLatUriDisruptionsIdRequestBuilder {
        return CoverageLonLatUriDisruptionsIdRequestBuilder(currentApi: self)
    }
    public func newCoverageRegionDisruptionsRequestBuilder() -> CoverageRegionDisruptionsRequestBuilder {
        return CoverageRegionDisruptionsRequestBuilder(currentApi: self)
    }
    public func newCoverageRegionDisruptionsIdRequestBuilder() -> CoverageRegionDisruptionsIdRequestBuilder {
        return CoverageRegionDisruptionsIdRequestBuilder(currentApi: self)
    }
    public func newCoverageRegionUriDisruptionsRequestBuilder() -> CoverageRegionUriDisruptionsRequestBuilder {
        return CoverageRegionUriDisruptionsRequestBuilder(currentApi: self)
    }
    public func newCoverageRegionUriDisruptionsIdRequestBuilder() -> CoverageRegionUriDisruptionsIdRequestBuilder {
        return CoverageRegionUriDisruptionsIdRequestBuilder(currentApi: self)
    }
}
