//
// LineGroupsApi.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

open class CoverageLonLatLineGroupsRequestBuilder: NSObject {
    let currentApi: LineGroupsApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var lat:Double? = nil
    var lon:Double? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var externalCode:String? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var filter:String? = nil
    var originalId:String? = nil

    public init(currentApi: LineGroupsApi) {
        self.currentApi = currentApi
    }

    open func withLat(_ lat: Double) -> CoverageLonLatLineGroupsRequestBuilder {
        self.lat = lat
        return self
    }
    open func withLon(_ lon: Double) -> CoverageLonLatLineGroupsRequestBuilder {
        self.lon = lon
        return self
    }
    open func withStartPage(_ startPage: Int32) -> CoverageLonLatLineGroupsRequestBuilder {
        self.startPage = startPage
        return self
    }
    open func withCount(_ count: Int32) -> CoverageLonLatLineGroupsRequestBuilder {
        self.count = count
        return self
    }
    open func withDepth(_ depth: Int32) -> CoverageLonLatLineGroupsRequestBuilder {
        self.depth = depth
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]) -> CoverageLonLatLineGroupsRequestBuilder {
        self.forbiddenId = forbiddenId
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]) -> CoverageLonLatLineGroupsRequestBuilder {
        self.forbiddenUris = forbiddenUris
        return self
    }
    open func withExternalCode(_ externalCode: String) -> CoverageLonLatLineGroupsRequestBuilder {
        self.externalCode = externalCode
        return self
    }
    open func withHeadsign(_ headsign: String) -> CoverageLonLatLineGroupsRequestBuilder {
        self.headsign = headsign
        return self
    }
    open func withShowCodes(_ showCodes: Bool) -> CoverageLonLatLineGroupsRequestBuilder {
        self.showCodes = showCodes
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel) -> CoverageLonLatLineGroupsRequestBuilder {
        self.odtLevel = odtLevel
        return self
    }
    open func withDistance(_ distance: Int32) -> CoverageLonLatLineGroupsRequestBuilder {
        self.distance = distance
        return self
    }
    open func withSince(_ since: Date) -> CoverageLonLatLineGroupsRequestBuilder {
        self.since = since
        return self
    }
    open func withUntil(_ until: Date) -> CoverageLonLatLineGroupsRequestBuilder {
        self.until = until
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool) -> CoverageLonLatLineGroupsRequestBuilder {
        self.disableGeojson = disableGeojson
        return self
    }
    open func withFilter(_ filter: String) -> CoverageLonLatLineGroupsRequestBuilder {
        self.filter = filter
        return self
    }
    open func withOriginalId(_ originalId: String) -> CoverageLonLatLineGroupsRequestBuilder {
        self.originalId = originalId
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{lon};{lat}/line_groups"

        if (lat != nil) {
            let latPreEscape: String = "\(lat!)"
            let latPostEscape: String = latPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lat}", with: latPostEscape, options: .literal, range: nil)
        }

        if (lon != nil) {
            let lonPreEscape: String = "\(lon!)"
            let lonPostEscape: String = lonPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lon}", with: lonPostEscape, options: .literal, range: nil)
        }

        let URLString = "https://api.navitia.io/v1" + path
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "filter": self.filter, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: LineGroups?,_ error: Error?) -> Void)) {
        if (self.lat == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
        }
        if (self.lon == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<LineGroups>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.lat == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
    }
    if (self.lon == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageLonLatLineGroupsIdRequestBuilder: NSObject {
    let currentApi: LineGroupsApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var lat:Double? = nil
    var lon:Double? = nil
    var id:String? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var externalCode:String? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var originalId:String? = nil

    public init(currentApi: LineGroupsApi) {
        self.currentApi = currentApi
    }

    open func withLat(_ lat: Double) -> CoverageLonLatLineGroupsIdRequestBuilder {
        self.lat = lat
        return self
    }
    open func withLon(_ lon: Double) -> CoverageLonLatLineGroupsIdRequestBuilder {
        self.lon = lon
        return self
    }
    open func withId(_ id: String) -> CoverageLonLatLineGroupsIdRequestBuilder {
        self.id = id
        return self
    }
    open func withStartPage(_ startPage: Int32) -> CoverageLonLatLineGroupsIdRequestBuilder {
        self.startPage = startPage
        return self
    }
    open func withCount(_ count: Int32) -> CoverageLonLatLineGroupsIdRequestBuilder {
        self.count = count
        return self
    }
    open func withDepth(_ depth: Int32) -> CoverageLonLatLineGroupsIdRequestBuilder {
        self.depth = depth
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]) -> CoverageLonLatLineGroupsIdRequestBuilder {
        self.forbiddenId = forbiddenId
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]) -> CoverageLonLatLineGroupsIdRequestBuilder {
        self.forbiddenUris = forbiddenUris
        return self
    }
    open func withExternalCode(_ externalCode: String) -> CoverageLonLatLineGroupsIdRequestBuilder {
        self.externalCode = externalCode
        return self
    }
    open func withHeadsign(_ headsign: String) -> CoverageLonLatLineGroupsIdRequestBuilder {
        self.headsign = headsign
        return self
    }
    open func withShowCodes(_ showCodes: Bool) -> CoverageLonLatLineGroupsIdRequestBuilder {
        self.showCodes = showCodes
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel) -> CoverageLonLatLineGroupsIdRequestBuilder {
        self.odtLevel = odtLevel
        return self
    }
    open func withDistance(_ distance: Int32) -> CoverageLonLatLineGroupsIdRequestBuilder {
        self.distance = distance
        return self
    }
    open func withSince(_ since: Date) -> CoverageLonLatLineGroupsIdRequestBuilder {
        self.since = since
        return self
    }
    open func withUntil(_ until: Date) -> CoverageLonLatLineGroupsIdRequestBuilder {
        self.until = until
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool) -> CoverageLonLatLineGroupsIdRequestBuilder {
        self.disableGeojson = disableGeojson
        return self
    }
    open func withOriginalId(_ originalId: String) -> CoverageLonLatLineGroupsIdRequestBuilder {
        self.originalId = originalId
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{lon};{lat}/line_groups/{id}"

        if (lat != nil) {
            let latPreEscape: String = "\(lat!)"
            let latPostEscape: String = latPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lat}", with: latPostEscape, options: .literal, range: nil)
        }

        if (lon != nil) {
            let lonPreEscape: String = "\(lon!)"
            let lonPostEscape: String = lonPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lon}", with: lonPostEscape, options: .literal, range: nil)
        }

        if (id != nil) {
            let idPreEscape: String = "\(id!)"
            let idPostEscape: String = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        }

        let URLString = "https://api.navitia.io/v1" + path
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: LineGroups?,_ error: Error?) -> Void)) {
        if (self.lat == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
        }
        if (self.lon == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
        }
        if (self.id == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<LineGroups>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.lat == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
    }
    if (self.lon == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
    }
    if (self.id == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageLonLatUriLineGroupsRequestBuilder: NSObject {
    let currentApi: LineGroupsApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var lat:Double? = nil
    var lon:Double? = nil
    var uri:String? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var externalCode:String? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var filter:String? = nil
    var originalId:String? = nil

    public init(currentApi: LineGroupsApi) {
        self.currentApi = currentApi
    }

    open func withLat(_ lat: Double) -> CoverageLonLatUriLineGroupsRequestBuilder {
        self.lat = lat
        return self
    }
    open func withLon(_ lon: Double) -> CoverageLonLatUriLineGroupsRequestBuilder {
        self.lon = lon
        return self
    }
    open func withUri(_ uri: String) -> CoverageLonLatUriLineGroupsRequestBuilder {
        self.uri = uri
        return self
    }
    open func withStartPage(_ startPage: Int32) -> CoverageLonLatUriLineGroupsRequestBuilder {
        self.startPage = startPage
        return self
    }
    open func withCount(_ count: Int32) -> CoverageLonLatUriLineGroupsRequestBuilder {
        self.count = count
        return self
    }
    open func withDepth(_ depth: Int32) -> CoverageLonLatUriLineGroupsRequestBuilder {
        self.depth = depth
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]) -> CoverageLonLatUriLineGroupsRequestBuilder {
        self.forbiddenId = forbiddenId
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]) -> CoverageLonLatUriLineGroupsRequestBuilder {
        self.forbiddenUris = forbiddenUris
        return self
    }
    open func withExternalCode(_ externalCode: String) -> CoverageLonLatUriLineGroupsRequestBuilder {
        self.externalCode = externalCode
        return self
    }
    open func withHeadsign(_ headsign: String) -> CoverageLonLatUriLineGroupsRequestBuilder {
        self.headsign = headsign
        return self
    }
    open func withShowCodes(_ showCodes: Bool) -> CoverageLonLatUriLineGroupsRequestBuilder {
        self.showCodes = showCodes
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel) -> CoverageLonLatUriLineGroupsRequestBuilder {
        self.odtLevel = odtLevel
        return self
    }
    open func withDistance(_ distance: Int32) -> CoverageLonLatUriLineGroupsRequestBuilder {
        self.distance = distance
        return self
    }
    open func withSince(_ since: Date) -> CoverageLonLatUriLineGroupsRequestBuilder {
        self.since = since
        return self
    }
    open func withUntil(_ until: Date) -> CoverageLonLatUriLineGroupsRequestBuilder {
        self.until = until
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool) -> CoverageLonLatUriLineGroupsRequestBuilder {
        self.disableGeojson = disableGeojson
        return self
    }
    open func withFilter(_ filter: String) -> CoverageLonLatUriLineGroupsRequestBuilder {
        self.filter = filter
        return self
    }
    open func withOriginalId(_ originalId: String) -> CoverageLonLatUriLineGroupsRequestBuilder {
        self.originalId = originalId
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{lon};{lat}/{uri}/line_groups"

        if (lat != nil) {
            let latPreEscape: String = "\(lat!)"
            let latPostEscape: String = latPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lat}", with: latPostEscape, options: .literal, range: nil)
        }

        if (lon != nil) {
            let lonPreEscape: String = "\(lon!)"
            let lonPostEscape: String = lonPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lon}", with: lonPostEscape, options: .literal, range: nil)
        }

        if (uri != nil) {
            let uriPreEscape: String = "\(uri!)"
            let uriPostEscape: String = uriPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{uri}", with: uriPostEscape, options: .literal, range: nil)
        }

        let URLString = "https://api.navitia.io/v1" + path
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "filter": self.filter, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: LineGroups?,_ error: Error?) -> Void)) {
        if (self.lat == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
        }
        if (self.lon == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
        }
        if (self.uri == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<LineGroups>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.lat == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
    }
    if (self.lon == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
    }
    if (self.uri == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageLonLatUriLineGroupsIdRequestBuilder: NSObject {
    let currentApi: LineGroupsApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var lat:Double? = nil
    var lon:Double? = nil
    var uri:String? = nil
    var id:String? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var externalCode:String? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var originalId:String? = nil

    public init(currentApi: LineGroupsApi) {
        self.currentApi = currentApi
    }

    open func withLat(_ lat: Double) -> CoverageLonLatUriLineGroupsIdRequestBuilder {
        self.lat = lat
        return self
    }
    open func withLon(_ lon: Double) -> CoverageLonLatUriLineGroupsIdRequestBuilder {
        self.lon = lon
        return self
    }
    open func withUri(_ uri: String) -> CoverageLonLatUriLineGroupsIdRequestBuilder {
        self.uri = uri
        return self
    }
    open func withId(_ id: String) -> CoverageLonLatUriLineGroupsIdRequestBuilder {
        self.id = id
        return self
    }
    open func withStartPage(_ startPage: Int32) -> CoverageLonLatUriLineGroupsIdRequestBuilder {
        self.startPage = startPage
        return self
    }
    open func withCount(_ count: Int32) -> CoverageLonLatUriLineGroupsIdRequestBuilder {
        self.count = count
        return self
    }
    open func withDepth(_ depth: Int32) -> CoverageLonLatUriLineGroupsIdRequestBuilder {
        self.depth = depth
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]) -> CoverageLonLatUriLineGroupsIdRequestBuilder {
        self.forbiddenId = forbiddenId
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]) -> CoverageLonLatUriLineGroupsIdRequestBuilder {
        self.forbiddenUris = forbiddenUris
        return self
    }
    open func withExternalCode(_ externalCode: String) -> CoverageLonLatUriLineGroupsIdRequestBuilder {
        self.externalCode = externalCode
        return self
    }
    open func withHeadsign(_ headsign: String) -> CoverageLonLatUriLineGroupsIdRequestBuilder {
        self.headsign = headsign
        return self
    }
    open func withShowCodes(_ showCodes: Bool) -> CoverageLonLatUriLineGroupsIdRequestBuilder {
        self.showCodes = showCodes
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel) -> CoverageLonLatUriLineGroupsIdRequestBuilder {
        self.odtLevel = odtLevel
        return self
    }
    open func withDistance(_ distance: Int32) -> CoverageLonLatUriLineGroupsIdRequestBuilder {
        self.distance = distance
        return self
    }
    open func withSince(_ since: Date) -> CoverageLonLatUriLineGroupsIdRequestBuilder {
        self.since = since
        return self
    }
    open func withUntil(_ until: Date) -> CoverageLonLatUriLineGroupsIdRequestBuilder {
        self.until = until
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool) -> CoverageLonLatUriLineGroupsIdRequestBuilder {
        self.disableGeojson = disableGeojson
        return self
    }
    open func withOriginalId(_ originalId: String) -> CoverageLonLatUriLineGroupsIdRequestBuilder {
        self.originalId = originalId
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{lon};{lat}/{uri}/line_groups/{id}"

        if (lat != nil) {
            let latPreEscape: String = "\(lat!)"
            let latPostEscape: String = latPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lat}", with: latPostEscape, options: .literal, range: nil)
        }

        if (lon != nil) {
            let lonPreEscape: String = "\(lon!)"
            let lonPostEscape: String = lonPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lon}", with: lonPostEscape, options: .literal, range: nil)
        }

        if (uri != nil) {
            let uriPreEscape: String = "\(uri!)"
            let uriPostEscape: String = uriPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{uri}", with: uriPostEscape, options: .literal, range: nil)
        }

        if (id != nil) {
            let idPreEscape: String = "\(id!)"
            let idPostEscape: String = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        }

        let URLString = "https://api.navitia.io/v1" + path
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: LineGroups?,_ error: Error?) -> Void)) {
        if (self.lat == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
        }
        if (self.lon == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
        }
        if (self.uri == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
        }
        if (self.id == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<LineGroups>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.lat == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
    }
    if (self.lon == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
    }
    if (self.uri == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
    }
    if (self.id == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageRegionLineGroupsRequestBuilder: NSObject {
    let currentApi: LineGroupsApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var region:String? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var externalCode:String? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var filter:String? = nil
    var originalId:String? = nil

    public init(currentApi: LineGroupsApi) {
        self.currentApi = currentApi
    }

    open func withRegion(_ region: String) -> CoverageRegionLineGroupsRequestBuilder {
        self.region = region
        return self
    }
    open func withStartPage(_ startPage: Int32) -> CoverageRegionLineGroupsRequestBuilder {
        self.startPage = startPage
        return self
    }
    open func withCount(_ count: Int32) -> CoverageRegionLineGroupsRequestBuilder {
        self.count = count
        return self
    }
    open func withDepth(_ depth: Int32) -> CoverageRegionLineGroupsRequestBuilder {
        self.depth = depth
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]) -> CoverageRegionLineGroupsRequestBuilder {
        self.forbiddenId = forbiddenId
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]) -> CoverageRegionLineGroupsRequestBuilder {
        self.forbiddenUris = forbiddenUris
        return self
    }
    open func withExternalCode(_ externalCode: String) -> CoverageRegionLineGroupsRequestBuilder {
        self.externalCode = externalCode
        return self
    }
    open func withHeadsign(_ headsign: String) -> CoverageRegionLineGroupsRequestBuilder {
        self.headsign = headsign
        return self
    }
    open func withShowCodes(_ showCodes: Bool) -> CoverageRegionLineGroupsRequestBuilder {
        self.showCodes = showCodes
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel) -> CoverageRegionLineGroupsRequestBuilder {
        self.odtLevel = odtLevel
        return self
    }
    open func withDistance(_ distance: Int32) -> CoverageRegionLineGroupsRequestBuilder {
        self.distance = distance
        return self
    }
    open func withSince(_ since: Date) -> CoverageRegionLineGroupsRequestBuilder {
        self.since = since
        return self
    }
    open func withUntil(_ until: Date) -> CoverageRegionLineGroupsRequestBuilder {
        self.until = until
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool) -> CoverageRegionLineGroupsRequestBuilder {
        self.disableGeojson = disableGeojson
        return self
    }
    open func withFilter(_ filter: String) -> CoverageRegionLineGroupsRequestBuilder {
        self.filter = filter
        return self
    }
    open func withOriginalId(_ originalId: String) -> CoverageRegionLineGroupsRequestBuilder {
        self.originalId = originalId
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{region}/line_groups"

        if (region != nil) {
            let regionPreEscape: String = "\(region!)"
            let regionPostEscape: String = regionPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{region}", with: regionPostEscape, options: .literal, range: nil)
        }

        let URLString = "https://api.navitia.io/v1" + path
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "filter": self.filter, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: LineGroups?,_ error: Error?) -> Void)) {
        if (self.region == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<LineGroups>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.region == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageRegionLineGroupsIdRequestBuilder: NSObject {
    let currentApi: LineGroupsApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var region:String? = nil
    var id:String? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var externalCode:String? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var originalId:String? = nil

    public init(currentApi: LineGroupsApi) {
        self.currentApi = currentApi
    }

    open func withRegion(_ region: String) -> CoverageRegionLineGroupsIdRequestBuilder {
        self.region = region
        return self
    }
    open func withId(_ id: String) -> CoverageRegionLineGroupsIdRequestBuilder {
        self.id = id
        return self
    }
    open func withStartPage(_ startPage: Int32) -> CoverageRegionLineGroupsIdRequestBuilder {
        self.startPage = startPage
        return self
    }
    open func withCount(_ count: Int32) -> CoverageRegionLineGroupsIdRequestBuilder {
        self.count = count
        return self
    }
    open func withDepth(_ depth: Int32) -> CoverageRegionLineGroupsIdRequestBuilder {
        self.depth = depth
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]) -> CoverageRegionLineGroupsIdRequestBuilder {
        self.forbiddenId = forbiddenId
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]) -> CoverageRegionLineGroupsIdRequestBuilder {
        self.forbiddenUris = forbiddenUris
        return self
    }
    open func withExternalCode(_ externalCode: String) -> CoverageRegionLineGroupsIdRequestBuilder {
        self.externalCode = externalCode
        return self
    }
    open func withHeadsign(_ headsign: String) -> CoverageRegionLineGroupsIdRequestBuilder {
        self.headsign = headsign
        return self
    }
    open func withShowCodes(_ showCodes: Bool) -> CoverageRegionLineGroupsIdRequestBuilder {
        self.showCodes = showCodes
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel) -> CoverageRegionLineGroupsIdRequestBuilder {
        self.odtLevel = odtLevel
        return self
    }
    open func withDistance(_ distance: Int32) -> CoverageRegionLineGroupsIdRequestBuilder {
        self.distance = distance
        return self
    }
    open func withSince(_ since: Date) -> CoverageRegionLineGroupsIdRequestBuilder {
        self.since = since
        return self
    }
    open func withUntil(_ until: Date) -> CoverageRegionLineGroupsIdRequestBuilder {
        self.until = until
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool) -> CoverageRegionLineGroupsIdRequestBuilder {
        self.disableGeojson = disableGeojson
        return self
    }
    open func withOriginalId(_ originalId: String) -> CoverageRegionLineGroupsIdRequestBuilder {
        self.originalId = originalId
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{region}/line_groups/{id}"

        if (region != nil) {
            let regionPreEscape: String = "\(region!)"
            let regionPostEscape: String = regionPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{region}", with: regionPostEscape, options: .literal, range: nil)
        }

        if (id != nil) {
            let idPreEscape: String = "\(id!)"
            let idPostEscape: String = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        }

        let URLString = "https://api.navitia.io/v1" + path
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: LineGroups?,_ error: Error?) -> Void)) {
        if (self.region == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
        }
        if (self.id == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<LineGroups>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.region == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
    }
    if (self.id == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageRegionUriLineGroupsRequestBuilder: NSObject {
    let currentApi: LineGroupsApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var region:String? = nil
    var uri:String? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var externalCode:String? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var filter:String? = nil
    var originalId:String? = nil

    public init(currentApi: LineGroupsApi) {
        self.currentApi = currentApi
    }

    open func withRegion(_ region: String) -> CoverageRegionUriLineGroupsRequestBuilder {
        self.region = region
        return self
    }
    open func withUri(_ uri: String) -> CoverageRegionUriLineGroupsRequestBuilder {
        self.uri = uri
        return self
    }
    open func withStartPage(_ startPage: Int32) -> CoverageRegionUriLineGroupsRequestBuilder {
        self.startPage = startPage
        return self
    }
    open func withCount(_ count: Int32) -> CoverageRegionUriLineGroupsRequestBuilder {
        self.count = count
        return self
    }
    open func withDepth(_ depth: Int32) -> CoverageRegionUriLineGroupsRequestBuilder {
        self.depth = depth
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]) -> CoverageRegionUriLineGroupsRequestBuilder {
        self.forbiddenId = forbiddenId
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]) -> CoverageRegionUriLineGroupsRequestBuilder {
        self.forbiddenUris = forbiddenUris
        return self
    }
    open func withExternalCode(_ externalCode: String) -> CoverageRegionUriLineGroupsRequestBuilder {
        self.externalCode = externalCode
        return self
    }
    open func withHeadsign(_ headsign: String) -> CoverageRegionUriLineGroupsRequestBuilder {
        self.headsign = headsign
        return self
    }
    open func withShowCodes(_ showCodes: Bool) -> CoverageRegionUriLineGroupsRequestBuilder {
        self.showCodes = showCodes
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel) -> CoverageRegionUriLineGroupsRequestBuilder {
        self.odtLevel = odtLevel
        return self
    }
    open func withDistance(_ distance: Int32) -> CoverageRegionUriLineGroupsRequestBuilder {
        self.distance = distance
        return self
    }
    open func withSince(_ since: Date) -> CoverageRegionUriLineGroupsRequestBuilder {
        self.since = since
        return self
    }
    open func withUntil(_ until: Date) -> CoverageRegionUriLineGroupsRequestBuilder {
        self.until = until
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool) -> CoverageRegionUriLineGroupsRequestBuilder {
        self.disableGeojson = disableGeojson
        return self
    }
    open func withFilter(_ filter: String) -> CoverageRegionUriLineGroupsRequestBuilder {
        self.filter = filter
        return self
    }
    open func withOriginalId(_ originalId: String) -> CoverageRegionUriLineGroupsRequestBuilder {
        self.originalId = originalId
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{region}/{uri}/line_groups"

        if (region != nil) {
            let regionPreEscape: String = "\(region!)"
            let regionPostEscape: String = regionPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{region}", with: regionPostEscape, options: .literal, range: nil)
        }

        if (uri != nil) {
            let uriPreEscape: String = "\(uri!)"
            let uriPostEscape: String = uriPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{uri}", with: uriPostEscape, options: .literal, range: nil)
        }

        let URLString = "https://api.navitia.io/v1" + path
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "filter": self.filter, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: LineGroups?,_ error: Error?) -> Void)) {
        if (self.region == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
        }
        if (self.uri == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<LineGroups>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.region == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
    }
    if (self.uri == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageRegionUriLineGroupsIdRequestBuilder: NSObject {
    let currentApi: LineGroupsApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var region:String? = nil
    var uri:String? = nil
    var id:String? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var externalCode:String? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var originalId:String? = nil

    public init(currentApi: LineGroupsApi) {
        self.currentApi = currentApi
    }

    open func withRegion(_ region: String) -> CoverageRegionUriLineGroupsIdRequestBuilder {
        self.region = region
        return self
    }
    open func withUri(_ uri: String) -> CoverageRegionUriLineGroupsIdRequestBuilder {
        self.uri = uri
        return self
    }
    open func withId(_ id: String) -> CoverageRegionUriLineGroupsIdRequestBuilder {
        self.id = id
        return self
    }
    open func withStartPage(_ startPage: Int32) -> CoverageRegionUriLineGroupsIdRequestBuilder {
        self.startPage = startPage
        return self
    }
    open func withCount(_ count: Int32) -> CoverageRegionUriLineGroupsIdRequestBuilder {
        self.count = count
        return self
    }
    open func withDepth(_ depth: Int32) -> CoverageRegionUriLineGroupsIdRequestBuilder {
        self.depth = depth
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]) -> CoverageRegionUriLineGroupsIdRequestBuilder {
        self.forbiddenId = forbiddenId
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]) -> CoverageRegionUriLineGroupsIdRequestBuilder {
        self.forbiddenUris = forbiddenUris
        return self
    }
    open func withExternalCode(_ externalCode: String) -> CoverageRegionUriLineGroupsIdRequestBuilder {
        self.externalCode = externalCode
        return self
    }
    open func withHeadsign(_ headsign: String) -> CoverageRegionUriLineGroupsIdRequestBuilder {
        self.headsign = headsign
        return self
    }
    open func withShowCodes(_ showCodes: Bool) -> CoverageRegionUriLineGroupsIdRequestBuilder {
        self.showCodes = showCodes
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel) -> CoverageRegionUriLineGroupsIdRequestBuilder {
        self.odtLevel = odtLevel
        return self
    }
    open func withDistance(_ distance: Int32) -> CoverageRegionUriLineGroupsIdRequestBuilder {
        self.distance = distance
        return self
    }
    open func withSince(_ since: Date) -> CoverageRegionUriLineGroupsIdRequestBuilder {
        self.since = since
        return self
    }
    open func withUntil(_ until: Date) -> CoverageRegionUriLineGroupsIdRequestBuilder {
        self.until = until
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool) -> CoverageRegionUriLineGroupsIdRequestBuilder {
        self.disableGeojson = disableGeojson
        return self
    }
    open func withOriginalId(_ originalId: String) -> CoverageRegionUriLineGroupsIdRequestBuilder {
        self.originalId = originalId
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{region}/{uri}/line_groups/{id}"

        if (region != nil) {
            let regionPreEscape: String = "\(region!)"
            let regionPostEscape: String = regionPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{region}", with: regionPostEscape, options: .literal, range: nil)
        }

        if (uri != nil) {
            let uriPreEscape: String = "\(uri!)"
            let uriPostEscape: String = uriPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{uri}", with: uriPostEscape, options: .literal, range: nil)
        }

        if (id != nil) {
            let idPreEscape: String = "\(id!)"
            let idPostEscape: String = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        }

        let URLString = "https://api.navitia.io/v1" + path
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: LineGroups?,_ error: Error?) -> Void)) {
        if (self.region == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
        }
        if (self.uri == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
        }
        if (self.id == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<LineGroups>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.region == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
    }
    if (self.uri == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
    }
    if (self.id == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class LineGroupsRequestBuilder: NSObject {
    let currentApi: LineGroupsApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var externalCode:String? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var filter:String? = nil
    var originalId:String? = nil

    public init(currentApi: LineGroupsApi) {
        self.currentApi = currentApi
    }

    open func withExternalCode(_ externalCode: String) -> LineGroupsRequestBuilder {
        self.externalCode = externalCode
        return self
    }
    open func withStartPage(_ startPage: Int32) -> LineGroupsRequestBuilder {
        self.startPage = startPage
        return self
    }
    open func withCount(_ count: Int32) -> LineGroupsRequestBuilder {
        self.count = count
        return self
    }
    open func withDepth(_ depth: Int32) -> LineGroupsRequestBuilder {
        self.depth = depth
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]) -> LineGroupsRequestBuilder {
        self.forbiddenId = forbiddenId
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]) -> LineGroupsRequestBuilder {
        self.forbiddenUris = forbiddenUris
        return self
    }
    open func withHeadsign(_ headsign: String) -> LineGroupsRequestBuilder {
        self.headsign = headsign
        return self
    }
    open func withShowCodes(_ showCodes: Bool) -> LineGroupsRequestBuilder {
        self.showCodes = showCodes
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel) -> LineGroupsRequestBuilder {
        self.odtLevel = odtLevel
        return self
    }
    open func withDistance(_ distance: Int32) -> LineGroupsRequestBuilder {
        self.distance = distance
        return self
    }
    open func withSince(_ since: Date) -> LineGroupsRequestBuilder {
        self.since = since
        return self
    }
    open func withUntil(_ until: Date) -> LineGroupsRequestBuilder {
        self.until = until
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool) -> LineGroupsRequestBuilder {
        self.disableGeojson = disableGeojson
        return self
    }
    open func withFilter(_ filter: String) -> LineGroupsRequestBuilder {
        self.filter = filter
        return self
    }
    open func withOriginalId(_ originalId: String) -> LineGroupsRequestBuilder {
        self.originalId = originalId
        return self
    }

    open func makeUrl() -> String {
        let path = "/line_groups"

        let URLString = "https://api.navitia.io/v1" + path
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode!, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "filter": self.filter, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: LineGroups?,_ error: Error?) -> Void)) {
        if (self.externalCode == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : externalCode"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<LineGroups>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.externalCode == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : externalCode"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}



open class LineGroupsApi: APIBase {
    let token: String

    public init(token: String) {
        self.token = token
    }

    public func newCoverageLonLatLineGroupsRequestBuilder() -> CoverageLonLatLineGroupsRequestBuilder {
        return CoverageLonLatLineGroupsRequestBuilder(currentApi: self)
    }
    public func newCoverageLonLatLineGroupsIdRequestBuilder() -> CoverageLonLatLineGroupsIdRequestBuilder {
        return CoverageLonLatLineGroupsIdRequestBuilder(currentApi: self)
    }
    public func newCoverageLonLatUriLineGroupsRequestBuilder() -> CoverageLonLatUriLineGroupsRequestBuilder {
        return CoverageLonLatUriLineGroupsRequestBuilder(currentApi: self)
    }
    public func newCoverageLonLatUriLineGroupsIdRequestBuilder() -> CoverageLonLatUriLineGroupsIdRequestBuilder {
        return CoverageLonLatUriLineGroupsIdRequestBuilder(currentApi: self)
    }
    public func newCoverageRegionLineGroupsRequestBuilder() -> CoverageRegionLineGroupsRequestBuilder {
        return CoverageRegionLineGroupsRequestBuilder(currentApi: self)
    }
    public func newCoverageRegionLineGroupsIdRequestBuilder() -> CoverageRegionLineGroupsIdRequestBuilder {
        return CoverageRegionLineGroupsIdRequestBuilder(currentApi: self)
    }
    public func newCoverageRegionUriLineGroupsRequestBuilder() -> CoverageRegionUriLineGroupsRequestBuilder {
        return CoverageRegionUriLineGroupsRequestBuilder(currentApi: self)
    }
    public func newCoverageRegionUriLineGroupsIdRequestBuilder() -> CoverageRegionUriLineGroupsIdRequestBuilder {
        return CoverageRegionUriLineGroupsIdRequestBuilder(currentApi: self)
    }
    public func newLineGroupsRequestBuilder() -> LineGroupsRequestBuilder {
        return LineGroupsRequestBuilder(currentApi: self)
    }
}
