//
// StopAreasApi.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

open class CoverageLonLatStopAreasRequestBuilder: NSObject {
    let currentApi: StopAreasApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var lat:Double? = nil
    var lon:Double? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var externalCode:String? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var disableDisruption:Bool? = nil
    var filter:String? = nil
    var tags:[String]? = nil
    var originalId:String? = nil
    var debugURL: String? = nil

    public init(currentApi: StopAreasApi) {
        self.currentApi = currentApi
    }

    open func withLat(_ lat: Double?) -> CoverageLonLatStopAreasRequestBuilder {
        self.lat = lat
        
        return self
    }
    open func withLon(_ lon: Double?) -> CoverageLonLatStopAreasRequestBuilder {
        self.lon = lon
        
        return self
    }
    open func withStartPage(_ startPage: Int32?) -> CoverageLonLatStopAreasRequestBuilder {
        self.startPage = startPage
        
        return self
    }
    open func withCount(_ count: Int32?) -> CoverageLonLatStopAreasRequestBuilder {
        self.count = count
        
        return self
    }
    open func withDepth(_ depth: Int32?) -> CoverageLonLatStopAreasRequestBuilder {
        self.depth = depth
        
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]?) -> CoverageLonLatStopAreasRequestBuilder {
        self.forbiddenId = forbiddenId
        
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]?) -> CoverageLonLatStopAreasRequestBuilder {
        self.forbiddenUris = forbiddenUris
        
        return self
    }
    open func withExternalCode(_ externalCode: String?) -> CoverageLonLatStopAreasRequestBuilder {
        self.externalCode = externalCode
        
        return self
    }
    open func withHeadsign(_ headsign: String?) -> CoverageLonLatStopAreasRequestBuilder {
        self.headsign = headsign
        
        return self
    }
    open func withShowCodes(_ showCodes: Bool?) -> CoverageLonLatStopAreasRequestBuilder {
        self.showCodes = showCodes
        
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel?) -> CoverageLonLatStopAreasRequestBuilder {
        self.odtLevel = odtLevel

        return self
    }
    open func withDistance(_ distance: Int32?) -> CoverageLonLatStopAreasRequestBuilder {
        self.distance = distance
        
        return self
    }
    open func withSince(_ since: Date?) -> CoverageLonLatStopAreasRequestBuilder {
        self.since = since
        
        return self
    }
    open func withUntil(_ until: Date?) -> CoverageLonLatStopAreasRequestBuilder {
        self.until = until
        
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool?) -> CoverageLonLatStopAreasRequestBuilder {
        self.disableGeojson = disableGeojson
        
        return self
    }
    open func withDisableDisruption(_ disableDisruption: Bool?) -> CoverageLonLatStopAreasRequestBuilder {
        self.disableDisruption = disableDisruption
        
        return self
    }
    open func withFilter(_ filter: String?) -> CoverageLonLatStopAreasRequestBuilder {
        self.filter = filter
        
        return self
    }
    open func withTags(_ tags: [String]?) -> CoverageLonLatStopAreasRequestBuilder {
        self.tags = tags
        
        return self
    }
    open func withOriginalId(_ originalId: String?) -> CoverageLonLatStopAreasRequestBuilder {
        self.originalId = originalId
        
        return self
    }



    open func withDebugURL(_ debugURL: String?) -> CoverageLonLatStopAreasRequestBuilder {
        self.debugURL = debugURL
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{lon};{lat}/stop_areas"

        if let lat = lat {
            let latPreEscape: String = "\(lat)"
            let latPostEscape: String = latPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lat}", with: latPostEscape, options: .literal, range: nil)
        }

        if let lon = lon {
            let lonPreEscape: String = "\(lon)"
            let lonPostEscape: String = lonPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lon}", with: lonPostEscape, options: .literal, range: nil)
        }

        let URLString = String(format: "%@%@", NavitiaSDKAPI.basePath, path)
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "disable_disruption": self.disableDisruption, 
            "filter": self.filter, 
            "tags[]": self.tags, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (debugURL ?? url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: StopAreas?,_ error: Error?) -> Void)) {
        if (self.lat == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
        }
        if (self.lon == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<StopAreas>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.lat == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
    }
    if (self.lon == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageLonLatStopAreasIdRequestBuilder: NSObject {
    let currentApi: StopAreasApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var lat:Double? = nil
    var lon:Double? = nil
    var id:String? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var externalCode:String? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var disableDisruption:Bool? = nil
    var tags:[String]? = nil
    var originalId:String? = nil
    var debugURL: String? = nil

    public init(currentApi: StopAreasApi) {
        self.currentApi = currentApi
    }

    open func withLat(_ lat: Double?) -> CoverageLonLatStopAreasIdRequestBuilder {
        self.lat = lat
        
        return self
    }
    open func withLon(_ lon: Double?) -> CoverageLonLatStopAreasIdRequestBuilder {
        self.lon = lon
        
        return self
    }
    open func withId(_ id: String?) -> CoverageLonLatStopAreasIdRequestBuilder {
        self.id = id
        
        return self
    }
    open func withStartPage(_ startPage: Int32?) -> CoverageLonLatStopAreasIdRequestBuilder {
        self.startPage = startPage
        
        return self
    }
    open func withCount(_ count: Int32?) -> CoverageLonLatStopAreasIdRequestBuilder {
        self.count = count
        
        return self
    }
    open func withDepth(_ depth: Int32?) -> CoverageLonLatStopAreasIdRequestBuilder {
        self.depth = depth
        
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]?) -> CoverageLonLatStopAreasIdRequestBuilder {
        self.forbiddenId = forbiddenId
        
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]?) -> CoverageLonLatStopAreasIdRequestBuilder {
        self.forbiddenUris = forbiddenUris
        
        return self
    }
    open func withExternalCode(_ externalCode: String?) -> CoverageLonLatStopAreasIdRequestBuilder {
        self.externalCode = externalCode
        
        return self
    }
    open func withHeadsign(_ headsign: String?) -> CoverageLonLatStopAreasIdRequestBuilder {
        self.headsign = headsign
        
        return self
    }
    open func withShowCodes(_ showCodes: Bool?) -> CoverageLonLatStopAreasIdRequestBuilder {
        self.showCodes = showCodes
        
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel?) -> CoverageLonLatStopAreasIdRequestBuilder {
        self.odtLevel = odtLevel

        return self
    }
    open func withDistance(_ distance: Int32?) -> CoverageLonLatStopAreasIdRequestBuilder {
        self.distance = distance
        
        return self
    }
    open func withSince(_ since: Date?) -> CoverageLonLatStopAreasIdRequestBuilder {
        self.since = since
        
        return self
    }
    open func withUntil(_ until: Date?) -> CoverageLonLatStopAreasIdRequestBuilder {
        self.until = until
        
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool?) -> CoverageLonLatStopAreasIdRequestBuilder {
        self.disableGeojson = disableGeojson
        
        return self
    }
    open func withDisableDisruption(_ disableDisruption: Bool?) -> CoverageLonLatStopAreasIdRequestBuilder {
        self.disableDisruption = disableDisruption
        
        return self
    }
    open func withTags(_ tags: [String]?) -> CoverageLonLatStopAreasIdRequestBuilder {
        self.tags = tags
        
        return self
    }
    open func withOriginalId(_ originalId: String?) -> CoverageLonLatStopAreasIdRequestBuilder {
        self.originalId = originalId
        
        return self
    }



    open func withDebugURL(_ debugURL: String?) -> CoverageLonLatStopAreasIdRequestBuilder {
        self.debugURL = debugURL
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{lon};{lat}/stop_areas/{id}"

        if let lat = lat {
            let latPreEscape: String = "\(lat)"
            let latPostEscape: String = latPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lat}", with: latPostEscape, options: .literal, range: nil)
        }

        if let lon = lon {
            let lonPreEscape: String = "\(lon)"
            let lonPostEscape: String = lonPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lon}", with: lonPostEscape, options: .literal, range: nil)
        }

        if let id = id {
            let idPreEscape: String = "\(id)"
            let idPostEscape: String = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        }

        let URLString = String(format: "%@%@", NavitiaSDKAPI.basePath, path)
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "disable_disruption": self.disableDisruption, 
            "tags[]": self.tags, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (debugURL ?? url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: StopAreas?,_ error: Error?) -> Void)) {
        if (self.lat == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
        }
        if (self.lon == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
        }
        if (self.id == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<StopAreas>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.lat == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
    }
    if (self.lon == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
    }
    if (self.id == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageLonLatUriStopAreasRequestBuilder: NSObject {
    let currentApi: StopAreasApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var lat:Double? = nil
    var lon:Double? = nil
    var uri:String? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var externalCode:String? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var disableDisruption:Bool? = nil
    var filter:String? = nil
    var tags:[String]? = nil
    var originalId:String? = nil
    var debugURL: String? = nil

    public init(currentApi: StopAreasApi) {
        self.currentApi = currentApi
    }

    open func withLat(_ lat: Double?) -> CoverageLonLatUriStopAreasRequestBuilder {
        self.lat = lat
        
        return self
    }
    open func withLon(_ lon: Double?) -> CoverageLonLatUriStopAreasRequestBuilder {
        self.lon = lon
        
        return self
    }
    open func withUri(_ uri: String?) -> CoverageLonLatUriStopAreasRequestBuilder {
        self.uri = uri
        
        return self
    }
    open func withStartPage(_ startPage: Int32?) -> CoverageLonLatUriStopAreasRequestBuilder {
        self.startPage = startPage
        
        return self
    }
    open func withCount(_ count: Int32?) -> CoverageLonLatUriStopAreasRequestBuilder {
        self.count = count
        
        return self
    }
    open func withDepth(_ depth: Int32?) -> CoverageLonLatUriStopAreasRequestBuilder {
        self.depth = depth
        
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]?) -> CoverageLonLatUriStopAreasRequestBuilder {
        self.forbiddenId = forbiddenId
        
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]?) -> CoverageLonLatUriStopAreasRequestBuilder {
        self.forbiddenUris = forbiddenUris
        
        return self
    }
    open func withExternalCode(_ externalCode: String?) -> CoverageLonLatUriStopAreasRequestBuilder {
        self.externalCode = externalCode
        
        return self
    }
    open func withHeadsign(_ headsign: String?) -> CoverageLonLatUriStopAreasRequestBuilder {
        self.headsign = headsign
        
        return self
    }
    open func withShowCodes(_ showCodes: Bool?) -> CoverageLonLatUriStopAreasRequestBuilder {
        self.showCodes = showCodes
        
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel?) -> CoverageLonLatUriStopAreasRequestBuilder {
        self.odtLevel = odtLevel

        return self
    }
    open func withDistance(_ distance: Int32?) -> CoverageLonLatUriStopAreasRequestBuilder {
        self.distance = distance
        
        return self
    }
    open func withSince(_ since: Date?) -> CoverageLonLatUriStopAreasRequestBuilder {
        self.since = since
        
        return self
    }
    open func withUntil(_ until: Date?) -> CoverageLonLatUriStopAreasRequestBuilder {
        self.until = until
        
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool?) -> CoverageLonLatUriStopAreasRequestBuilder {
        self.disableGeojson = disableGeojson
        
        return self
    }
    open func withDisableDisruption(_ disableDisruption: Bool?) -> CoverageLonLatUriStopAreasRequestBuilder {
        self.disableDisruption = disableDisruption
        
        return self
    }
    open func withFilter(_ filter: String?) -> CoverageLonLatUriStopAreasRequestBuilder {
        self.filter = filter
        
        return self
    }
    open func withTags(_ tags: [String]?) -> CoverageLonLatUriStopAreasRequestBuilder {
        self.tags = tags
        
        return self
    }
    open func withOriginalId(_ originalId: String?) -> CoverageLonLatUriStopAreasRequestBuilder {
        self.originalId = originalId
        
        return self
    }



    open func withDebugURL(_ debugURL: String?) -> CoverageLonLatUriStopAreasRequestBuilder {
        self.debugURL = debugURL
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{lon};{lat}/{uri}/stop_areas"

        if let lat = lat {
            let latPreEscape: String = "\(lat)"
            let latPostEscape: String = latPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lat}", with: latPostEscape, options: .literal, range: nil)
        }

        if let lon = lon {
            let lonPreEscape: String = "\(lon)"
            let lonPostEscape: String = lonPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lon}", with: lonPostEscape, options: .literal, range: nil)
        }

        if let uri = uri {
            let uriPreEscape: String = "\(uri)"
            let uriPostEscape: String = uriPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{uri}", with: uriPostEscape, options: .literal, range: nil)
        }

        let URLString = String(format: "%@%@", NavitiaSDKAPI.basePath, path)
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "disable_disruption": self.disableDisruption, 
            "filter": self.filter, 
            "tags[]": self.tags, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (debugURL ?? url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: StopAreas?,_ error: Error?) -> Void)) {
        if (self.lat == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
        }
        if (self.lon == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
        }
        if (self.uri == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<StopAreas>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.lat == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
    }
    if (self.lon == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
    }
    if (self.uri == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageLonLatUriStopAreasIdRequestBuilder: NSObject {
    let currentApi: StopAreasApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var lat:Double? = nil
    var lon:Double? = nil
    var uri:String? = nil
    var id:String? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var externalCode:String? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var disableDisruption:Bool? = nil
    var tags:[String]? = nil
    var originalId:String? = nil
    var debugURL: String? = nil

    public init(currentApi: StopAreasApi) {
        self.currentApi = currentApi
    }

    open func withLat(_ lat: Double?) -> CoverageLonLatUriStopAreasIdRequestBuilder {
        self.lat = lat
        
        return self
    }
    open func withLon(_ lon: Double?) -> CoverageLonLatUriStopAreasIdRequestBuilder {
        self.lon = lon
        
        return self
    }
    open func withUri(_ uri: String?) -> CoverageLonLatUriStopAreasIdRequestBuilder {
        self.uri = uri
        
        return self
    }
    open func withId(_ id: String?) -> CoverageLonLatUriStopAreasIdRequestBuilder {
        self.id = id
        
        return self
    }
    open func withStartPage(_ startPage: Int32?) -> CoverageLonLatUriStopAreasIdRequestBuilder {
        self.startPage = startPage
        
        return self
    }
    open func withCount(_ count: Int32?) -> CoverageLonLatUriStopAreasIdRequestBuilder {
        self.count = count
        
        return self
    }
    open func withDepth(_ depth: Int32?) -> CoverageLonLatUriStopAreasIdRequestBuilder {
        self.depth = depth
        
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]?) -> CoverageLonLatUriStopAreasIdRequestBuilder {
        self.forbiddenId = forbiddenId
        
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]?) -> CoverageLonLatUriStopAreasIdRequestBuilder {
        self.forbiddenUris = forbiddenUris
        
        return self
    }
    open func withExternalCode(_ externalCode: String?) -> CoverageLonLatUriStopAreasIdRequestBuilder {
        self.externalCode = externalCode
        
        return self
    }
    open func withHeadsign(_ headsign: String?) -> CoverageLonLatUriStopAreasIdRequestBuilder {
        self.headsign = headsign
        
        return self
    }
    open func withShowCodes(_ showCodes: Bool?) -> CoverageLonLatUriStopAreasIdRequestBuilder {
        self.showCodes = showCodes
        
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel?) -> CoverageLonLatUriStopAreasIdRequestBuilder {
        self.odtLevel = odtLevel

        return self
    }
    open func withDistance(_ distance: Int32?) -> CoverageLonLatUriStopAreasIdRequestBuilder {
        self.distance = distance
        
        return self
    }
    open func withSince(_ since: Date?) -> CoverageLonLatUriStopAreasIdRequestBuilder {
        self.since = since
        
        return self
    }
    open func withUntil(_ until: Date?) -> CoverageLonLatUriStopAreasIdRequestBuilder {
        self.until = until
        
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool?) -> CoverageLonLatUriStopAreasIdRequestBuilder {
        self.disableGeojson = disableGeojson
        
        return self
    }
    open func withDisableDisruption(_ disableDisruption: Bool?) -> CoverageLonLatUriStopAreasIdRequestBuilder {
        self.disableDisruption = disableDisruption
        
        return self
    }
    open func withTags(_ tags: [String]?) -> CoverageLonLatUriStopAreasIdRequestBuilder {
        self.tags = tags
        
        return self
    }
    open func withOriginalId(_ originalId: String?) -> CoverageLonLatUriStopAreasIdRequestBuilder {
        self.originalId = originalId
        
        return self
    }



    open func withDebugURL(_ debugURL: String?) -> CoverageLonLatUriStopAreasIdRequestBuilder {
        self.debugURL = debugURL
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{lon};{lat}/{uri}/stop_areas/{id}"

        if let lat = lat {
            let latPreEscape: String = "\(lat)"
            let latPostEscape: String = latPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lat}", with: latPostEscape, options: .literal, range: nil)
        }

        if let lon = lon {
            let lonPreEscape: String = "\(lon)"
            let lonPostEscape: String = lonPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lon}", with: lonPostEscape, options: .literal, range: nil)
        }

        if let uri = uri {
            let uriPreEscape: String = "\(uri)"
            let uriPostEscape: String = uriPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{uri}", with: uriPostEscape, options: .literal, range: nil)
        }

        if let id = id {
            let idPreEscape: String = "\(id)"
            let idPostEscape: String = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        }

        let URLString = String(format: "%@%@", NavitiaSDKAPI.basePath, path)
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "disable_disruption": self.disableDisruption, 
            "tags[]": self.tags, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (debugURL ?? url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: StopAreas?,_ error: Error?) -> Void)) {
        if (self.lat == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
        }
        if (self.lon == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
        }
        if (self.uri == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
        }
        if (self.id == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<StopAreas>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.lat == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
    }
    if (self.lon == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
    }
    if (self.uri == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
    }
    if (self.id == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageRegionStopAreasRequestBuilder: NSObject {
    let currentApi: StopAreasApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var region:String? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var externalCode:String? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var disableDisruption:Bool? = nil
    var filter:String? = nil
    var tags:[String]? = nil
    var originalId:String? = nil
    var debugURL: String? = nil

    public init(currentApi: StopAreasApi) {
        self.currentApi = currentApi
    }

    open func withRegion(_ region: String?) -> CoverageRegionStopAreasRequestBuilder {
        self.region = region
        
        return self
    }
    open func withStartPage(_ startPage: Int32?) -> CoverageRegionStopAreasRequestBuilder {
        self.startPage = startPage
        
        return self
    }
    open func withCount(_ count: Int32?) -> CoverageRegionStopAreasRequestBuilder {
        self.count = count
        
        return self
    }
    open func withDepth(_ depth: Int32?) -> CoverageRegionStopAreasRequestBuilder {
        self.depth = depth
        
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]?) -> CoverageRegionStopAreasRequestBuilder {
        self.forbiddenId = forbiddenId
        
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]?) -> CoverageRegionStopAreasRequestBuilder {
        self.forbiddenUris = forbiddenUris
        
        return self
    }
    open func withExternalCode(_ externalCode: String?) -> CoverageRegionStopAreasRequestBuilder {
        self.externalCode = externalCode
        
        return self
    }
    open func withHeadsign(_ headsign: String?) -> CoverageRegionStopAreasRequestBuilder {
        self.headsign = headsign
        
        return self
    }
    open func withShowCodes(_ showCodes: Bool?) -> CoverageRegionStopAreasRequestBuilder {
        self.showCodes = showCodes
        
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel?) -> CoverageRegionStopAreasRequestBuilder {
        self.odtLevel = odtLevel

        return self
    }
    open func withDistance(_ distance: Int32?) -> CoverageRegionStopAreasRequestBuilder {
        self.distance = distance
        
        return self
    }
    open func withSince(_ since: Date?) -> CoverageRegionStopAreasRequestBuilder {
        self.since = since
        
        return self
    }
    open func withUntil(_ until: Date?) -> CoverageRegionStopAreasRequestBuilder {
        self.until = until
        
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool?) -> CoverageRegionStopAreasRequestBuilder {
        self.disableGeojson = disableGeojson
        
        return self
    }
    open func withDisableDisruption(_ disableDisruption: Bool?) -> CoverageRegionStopAreasRequestBuilder {
        self.disableDisruption = disableDisruption
        
        return self
    }
    open func withFilter(_ filter: String?) -> CoverageRegionStopAreasRequestBuilder {
        self.filter = filter
        
        return self
    }
    open func withTags(_ tags: [String]?) -> CoverageRegionStopAreasRequestBuilder {
        self.tags = tags
        
        return self
    }
    open func withOriginalId(_ originalId: String?) -> CoverageRegionStopAreasRequestBuilder {
        self.originalId = originalId
        
        return self
    }



    open func withDebugURL(_ debugURL: String?) -> CoverageRegionStopAreasRequestBuilder {
        self.debugURL = debugURL
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{region}/stop_areas"

        if let region = region {
            let regionPreEscape: String = "\(region)"
            let regionPostEscape: String = regionPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{region}", with: regionPostEscape, options: .literal, range: nil)
        }

        let URLString = String(format: "%@%@", NavitiaSDKAPI.basePath, path)
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "disable_disruption": self.disableDisruption, 
            "filter": self.filter, 
            "tags[]": self.tags, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (debugURL ?? url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: StopAreas?,_ error: Error?) -> Void)) {
        if (self.region == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<StopAreas>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.region == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageRegionStopAreasIdRequestBuilder: NSObject {
    let currentApi: StopAreasApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var region:String? = nil
    var id:String? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var externalCode:String? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var disableDisruption:Bool? = nil
    var tags:[String]? = nil
    var originalId:String? = nil
    var debugURL: String? = nil

    public init(currentApi: StopAreasApi) {
        self.currentApi = currentApi
    }

    open func withRegion(_ region: String?) -> CoverageRegionStopAreasIdRequestBuilder {
        self.region = region
        
        return self
    }
    open func withId(_ id: String?) -> CoverageRegionStopAreasIdRequestBuilder {
        self.id = id
        
        return self
    }
    open func withStartPage(_ startPage: Int32?) -> CoverageRegionStopAreasIdRequestBuilder {
        self.startPage = startPage
        
        return self
    }
    open func withCount(_ count: Int32?) -> CoverageRegionStopAreasIdRequestBuilder {
        self.count = count
        
        return self
    }
    open func withDepth(_ depth: Int32?) -> CoverageRegionStopAreasIdRequestBuilder {
        self.depth = depth
        
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]?) -> CoverageRegionStopAreasIdRequestBuilder {
        self.forbiddenId = forbiddenId
        
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]?) -> CoverageRegionStopAreasIdRequestBuilder {
        self.forbiddenUris = forbiddenUris
        
        return self
    }
    open func withExternalCode(_ externalCode: String?) -> CoverageRegionStopAreasIdRequestBuilder {
        self.externalCode = externalCode
        
        return self
    }
    open func withHeadsign(_ headsign: String?) -> CoverageRegionStopAreasIdRequestBuilder {
        self.headsign = headsign
        
        return self
    }
    open func withShowCodes(_ showCodes: Bool?) -> CoverageRegionStopAreasIdRequestBuilder {
        self.showCodes = showCodes
        
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel?) -> CoverageRegionStopAreasIdRequestBuilder {
        self.odtLevel = odtLevel

        return self
    }
    open func withDistance(_ distance: Int32?) -> CoverageRegionStopAreasIdRequestBuilder {
        self.distance = distance
        
        return self
    }
    open func withSince(_ since: Date?) -> CoverageRegionStopAreasIdRequestBuilder {
        self.since = since
        
        return self
    }
    open func withUntil(_ until: Date?) -> CoverageRegionStopAreasIdRequestBuilder {
        self.until = until
        
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool?) -> CoverageRegionStopAreasIdRequestBuilder {
        self.disableGeojson = disableGeojson
        
        return self
    }
    open func withDisableDisruption(_ disableDisruption: Bool?) -> CoverageRegionStopAreasIdRequestBuilder {
        self.disableDisruption = disableDisruption
        
        return self
    }
    open func withTags(_ tags: [String]?) -> CoverageRegionStopAreasIdRequestBuilder {
        self.tags = tags
        
        return self
    }
    open func withOriginalId(_ originalId: String?) -> CoverageRegionStopAreasIdRequestBuilder {
        self.originalId = originalId
        
        return self
    }



    open func withDebugURL(_ debugURL: String?) -> CoverageRegionStopAreasIdRequestBuilder {
        self.debugURL = debugURL
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{region}/stop_areas/{id}"

        if let region = region {
            let regionPreEscape: String = "\(region)"
            let regionPostEscape: String = regionPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{region}", with: regionPostEscape, options: .literal, range: nil)
        }

        if let id = id {
            let idPreEscape: String = "\(id)"
            let idPostEscape: String = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        }

        let URLString = String(format: "%@%@", NavitiaSDKAPI.basePath, path)
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "disable_disruption": self.disableDisruption, 
            "tags[]": self.tags, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (debugURL ?? url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: StopAreas?,_ error: Error?) -> Void)) {
        if (self.region == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
        }
        if (self.id == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<StopAreas>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.region == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
    }
    if (self.id == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageRegionUriStopAreasRequestBuilder: NSObject {
    let currentApi: StopAreasApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var region:String? = nil
    var uri:String? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var externalCode:String? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var disableDisruption:Bool? = nil
    var filter:String? = nil
    var tags:[String]? = nil
    var originalId:String? = nil
    var debugURL: String? = nil

    public init(currentApi: StopAreasApi) {
        self.currentApi = currentApi
    }

    open func withRegion(_ region: String?) -> CoverageRegionUriStopAreasRequestBuilder {
        self.region = region
        
        return self
    }
    open func withUri(_ uri: String?) -> CoverageRegionUriStopAreasRequestBuilder {
        self.uri = uri
        
        return self
    }
    open func withStartPage(_ startPage: Int32?) -> CoverageRegionUriStopAreasRequestBuilder {
        self.startPage = startPage
        
        return self
    }
    open func withCount(_ count: Int32?) -> CoverageRegionUriStopAreasRequestBuilder {
        self.count = count
        
        return self
    }
    open func withDepth(_ depth: Int32?) -> CoverageRegionUriStopAreasRequestBuilder {
        self.depth = depth
        
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]?) -> CoverageRegionUriStopAreasRequestBuilder {
        self.forbiddenId = forbiddenId
        
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]?) -> CoverageRegionUriStopAreasRequestBuilder {
        self.forbiddenUris = forbiddenUris
        
        return self
    }
    open func withExternalCode(_ externalCode: String?) -> CoverageRegionUriStopAreasRequestBuilder {
        self.externalCode = externalCode
        
        return self
    }
    open func withHeadsign(_ headsign: String?) -> CoverageRegionUriStopAreasRequestBuilder {
        self.headsign = headsign
        
        return self
    }
    open func withShowCodes(_ showCodes: Bool?) -> CoverageRegionUriStopAreasRequestBuilder {
        self.showCodes = showCodes
        
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel?) -> CoverageRegionUriStopAreasRequestBuilder {
        self.odtLevel = odtLevel

        return self
    }
    open func withDistance(_ distance: Int32?) -> CoverageRegionUriStopAreasRequestBuilder {
        self.distance = distance
        
        return self
    }
    open func withSince(_ since: Date?) -> CoverageRegionUriStopAreasRequestBuilder {
        self.since = since
        
        return self
    }
    open func withUntil(_ until: Date?) -> CoverageRegionUriStopAreasRequestBuilder {
        self.until = until
        
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool?) -> CoverageRegionUriStopAreasRequestBuilder {
        self.disableGeojson = disableGeojson
        
        return self
    }
    open func withDisableDisruption(_ disableDisruption: Bool?) -> CoverageRegionUriStopAreasRequestBuilder {
        self.disableDisruption = disableDisruption
        
        return self
    }
    open func withFilter(_ filter: String?) -> CoverageRegionUriStopAreasRequestBuilder {
        self.filter = filter
        
        return self
    }
    open func withTags(_ tags: [String]?) -> CoverageRegionUriStopAreasRequestBuilder {
        self.tags = tags
        
        return self
    }
    open func withOriginalId(_ originalId: String?) -> CoverageRegionUriStopAreasRequestBuilder {
        self.originalId = originalId
        
        return self
    }



    open func withDebugURL(_ debugURL: String?) -> CoverageRegionUriStopAreasRequestBuilder {
        self.debugURL = debugURL
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{region}/{uri}/stop_areas"

        if let region = region {
            let regionPreEscape: String = "\(region)"
            let regionPostEscape: String = regionPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{region}", with: regionPostEscape, options: .literal, range: nil)
        }

        if let uri = uri {
            let uriPreEscape: String = "\(uri)"
            let uriPostEscape: String = uriPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{uri}", with: uriPostEscape, options: .literal, range: nil)
        }

        let URLString = String(format: "%@%@", NavitiaSDKAPI.basePath, path)
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "disable_disruption": self.disableDisruption, 
            "filter": self.filter, 
            "tags[]": self.tags, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (debugURL ?? url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: StopAreas?,_ error: Error?) -> Void)) {
        if (self.region == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
        }
        if (self.uri == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<StopAreas>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.region == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
    }
    if (self.uri == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageRegionUriStopAreasIdRequestBuilder: NSObject {
    let currentApi: StopAreasApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var region:String? = nil
    var uri:String? = nil
    var id:String? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var externalCode:String? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var disableDisruption:Bool? = nil
    var tags:[String]? = nil
    var originalId:String? = nil
    var debugURL: String? = nil

    public init(currentApi: StopAreasApi) {
        self.currentApi = currentApi
    }

    open func withRegion(_ region: String?) -> CoverageRegionUriStopAreasIdRequestBuilder {
        self.region = region
        
        return self
    }
    open func withUri(_ uri: String?) -> CoverageRegionUriStopAreasIdRequestBuilder {
        self.uri = uri
        
        return self
    }
    open func withId(_ id: String?) -> CoverageRegionUriStopAreasIdRequestBuilder {
        self.id = id
        
        return self
    }
    open func withStartPage(_ startPage: Int32?) -> CoverageRegionUriStopAreasIdRequestBuilder {
        self.startPage = startPage
        
        return self
    }
    open func withCount(_ count: Int32?) -> CoverageRegionUriStopAreasIdRequestBuilder {
        self.count = count
        
        return self
    }
    open func withDepth(_ depth: Int32?) -> CoverageRegionUriStopAreasIdRequestBuilder {
        self.depth = depth
        
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]?) -> CoverageRegionUriStopAreasIdRequestBuilder {
        self.forbiddenId = forbiddenId
        
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]?) -> CoverageRegionUriStopAreasIdRequestBuilder {
        self.forbiddenUris = forbiddenUris
        
        return self
    }
    open func withExternalCode(_ externalCode: String?) -> CoverageRegionUriStopAreasIdRequestBuilder {
        self.externalCode = externalCode
        
        return self
    }
    open func withHeadsign(_ headsign: String?) -> CoverageRegionUriStopAreasIdRequestBuilder {
        self.headsign = headsign
        
        return self
    }
    open func withShowCodes(_ showCodes: Bool?) -> CoverageRegionUriStopAreasIdRequestBuilder {
        self.showCodes = showCodes
        
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel?) -> CoverageRegionUriStopAreasIdRequestBuilder {
        self.odtLevel = odtLevel

        return self
    }
    open func withDistance(_ distance: Int32?) -> CoverageRegionUriStopAreasIdRequestBuilder {
        self.distance = distance
        
        return self
    }
    open func withSince(_ since: Date?) -> CoverageRegionUriStopAreasIdRequestBuilder {
        self.since = since
        
        return self
    }
    open func withUntil(_ until: Date?) -> CoverageRegionUriStopAreasIdRequestBuilder {
        self.until = until
        
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool?) -> CoverageRegionUriStopAreasIdRequestBuilder {
        self.disableGeojson = disableGeojson
        
        return self
    }
    open func withDisableDisruption(_ disableDisruption: Bool?) -> CoverageRegionUriStopAreasIdRequestBuilder {
        self.disableDisruption = disableDisruption
        
        return self
    }
    open func withTags(_ tags: [String]?) -> CoverageRegionUriStopAreasIdRequestBuilder {
        self.tags = tags
        
        return self
    }
    open func withOriginalId(_ originalId: String?) -> CoverageRegionUriStopAreasIdRequestBuilder {
        self.originalId = originalId
        
        return self
    }



    open func withDebugURL(_ debugURL: String?) -> CoverageRegionUriStopAreasIdRequestBuilder {
        self.debugURL = debugURL
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{region}/{uri}/stop_areas/{id}"

        if let region = region {
            let regionPreEscape: String = "\(region)"
            let regionPostEscape: String = regionPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{region}", with: regionPostEscape, options: .literal, range: nil)
        }

        if let uri = uri {
            let uriPreEscape: String = "\(uri)"
            let uriPostEscape: String = uriPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{uri}", with: uriPostEscape, options: .literal, range: nil)
        }

        if let id = id {
            let idPreEscape: String = "\(id)"
            let idPostEscape: String = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        }

        let URLString = String(format: "%@%@", NavitiaSDKAPI.basePath, path)
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "disable_disruption": self.disableDisruption, 
            "tags[]": self.tags, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (debugURL ?? url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: StopAreas?,_ error: Error?) -> Void)) {
        if (self.region == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
        }
        if (self.uri == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
        }
        if (self.id == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<StopAreas>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.region == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
    }
    if (self.uri == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
    }
    if (self.id == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class StopAreasRequestBuilder: NSObject {
    let currentApi: StopAreasApi

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var externalCode:String? = nil
    var startPage:Int32? = nil
    var count:Int32? = nil
    var depth:Int32? = nil
    var forbiddenId:[String]? = nil
    var forbiddenUris:[String]? = nil
    var headsign:String? = nil
    var showCodes:Bool? = nil
    var odtLevel: OdtLevel? = nil
    var distance:Int32? = nil
    var since:Date? = nil
    var until:Date? = nil
    var disableGeojson:Bool? = nil
    var disableDisruption:Bool? = nil
    var filter:String? = nil
    var tags:[String]? = nil
    var originalId:String? = nil
    var debugURL: String? = nil

    public init(currentApi: StopAreasApi) {
        self.currentApi = currentApi
    }

    open func withExternalCode(_ externalCode: String?) -> StopAreasRequestBuilder {
        self.externalCode = externalCode
        
        return self
    }
    open func withStartPage(_ startPage: Int32?) -> StopAreasRequestBuilder {
        self.startPage = startPage
        
        return self
    }
    open func withCount(_ count: Int32?) -> StopAreasRequestBuilder {
        self.count = count
        
        return self
    }
    open func withDepth(_ depth: Int32?) -> StopAreasRequestBuilder {
        self.depth = depth
        
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]?) -> StopAreasRequestBuilder {
        self.forbiddenId = forbiddenId
        
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]?) -> StopAreasRequestBuilder {
        self.forbiddenUris = forbiddenUris
        
        return self
    }
    open func withHeadsign(_ headsign: String?) -> StopAreasRequestBuilder {
        self.headsign = headsign
        
        return self
    }
    open func withShowCodes(_ showCodes: Bool?) -> StopAreasRequestBuilder {
        self.showCodes = showCodes
        
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel?) -> StopAreasRequestBuilder {
        self.odtLevel = odtLevel

        return self
    }
    open func withDistance(_ distance: Int32?) -> StopAreasRequestBuilder {
        self.distance = distance
        
        return self
    }
    open func withSince(_ since: Date?) -> StopAreasRequestBuilder {
        self.since = since
        
        return self
    }
    open func withUntil(_ until: Date?) -> StopAreasRequestBuilder {
        self.until = until
        
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool?) -> StopAreasRequestBuilder {
        self.disableGeojson = disableGeojson
        
        return self
    }
    open func withDisableDisruption(_ disableDisruption: Bool?) -> StopAreasRequestBuilder {
        self.disableDisruption = disableDisruption
        
        return self
    }
    open func withFilter(_ filter: String?) -> StopAreasRequestBuilder {
        self.filter = filter
        
        return self
    }
    open func withTags(_ tags: [String]?) -> StopAreasRequestBuilder {
        self.tags = tags
        
        return self
    }
    open func withOriginalId(_ originalId: String?) -> StopAreasRequestBuilder {
        self.originalId = originalId
        
        return self
    }



    open func withDebugURL(_ debugURL: String?) -> StopAreasRequestBuilder {
        self.debugURL = debugURL
        return self
    }

    open func makeUrl() -> String {
        let path = "/stop_areas"

        let URLString = String(format: "%@%@", NavitiaSDKAPI.basePath, path)
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode!, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since?.encodeToJSON(), 
            "until": self.until?.encodeToJSON(), 
            "disable_geojson": self.disableGeojson, 
            "disable_disruption": self.disableDisruption, 
            "filter": self.filter, 
            "tags[]": self.tags, 
            "original_id": self.originalId
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (debugURL ?? url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: StopAreas?,_ error: Error?) -> Void)) {
        if (self.externalCode == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : externalCode"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<StopAreas>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.externalCode == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : externalCode"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}



open class StopAreasApi: APIBase {
    let token: String

    public init(token: String) {
        self.token = token
    }

    public func newCoverageLonLatStopAreasRequestBuilder() -> CoverageLonLatStopAreasRequestBuilder {
        return CoverageLonLatStopAreasRequestBuilder(currentApi: self)
    }
    public func newCoverageLonLatStopAreasIdRequestBuilder() -> CoverageLonLatStopAreasIdRequestBuilder {
        return CoverageLonLatStopAreasIdRequestBuilder(currentApi: self)
    }
    public func newCoverageLonLatUriStopAreasRequestBuilder() -> CoverageLonLatUriStopAreasRequestBuilder {
        return CoverageLonLatUriStopAreasRequestBuilder(currentApi: self)
    }
    public func newCoverageLonLatUriStopAreasIdRequestBuilder() -> CoverageLonLatUriStopAreasIdRequestBuilder {
        return CoverageLonLatUriStopAreasIdRequestBuilder(currentApi: self)
    }
    public func newCoverageRegionStopAreasRequestBuilder() -> CoverageRegionStopAreasRequestBuilder {
        return CoverageRegionStopAreasRequestBuilder(currentApi: self)
    }
    public func newCoverageRegionStopAreasIdRequestBuilder() -> CoverageRegionStopAreasIdRequestBuilder {
        return CoverageRegionStopAreasIdRequestBuilder(currentApi: self)
    }
    public func newCoverageRegionUriStopAreasRequestBuilder() -> CoverageRegionUriStopAreasRequestBuilder {
        return CoverageRegionUriStopAreasRequestBuilder(currentApi: self)
    }
    public func newCoverageRegionUriStopAreasIdRequestBuilder() -> CoverageRegionUriStopAreasIdRequestBuilder {
        return CoverageRegionUriStopAreasIdRequestBuilder(currentApi: self)
    }
    public func newStopAreasRequestBuilder() -> StopAreasRequestBuilder {
        return StopAreasRequestBuilder(currentApi: self)
    }
}
