# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
    desc "Running tests"
    lane :tests do
      run_tests(scheme: "NavitiaSDKUITests",
                clean:  true)
    end

    desc "Submit a new Beta Build to Apple TestFlight"
    desc "This will also make sure the profile is up to date"
    lane :beta do
        increment_build_number
        get_certificates(
            team_id: "AK7DPF549M"
        )
        get_provisioning_profile
        update_app_identifier(
            xcodeproj: "NavitiaSDKUI-Example.xcodeproj",
            plist_path: "NavitiaSDKUI-Example/Info.plist",
            app_identifier: "com.kisio.navitia.ui.sample"
        )
        update_project_provisioning(
            build_configuration: "Release"
        )
        update_info_plist
        update_project_team(
            teamid: "AK7DPF549M"
        )
        cocoapods
        build_ios_app
        UI.message "
        #######################################################################
        "
        UI.success "Build successfully finish"
        UI.message "
        #######################################################################
        "
        upload_to_testflight(
            skip_waiting_for_build_processing: true
        )
    end
end
