//
// Note.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Note: JSONEncodable, Mappable, Codable {

    public enum Category: String, Codable { 
        case comment = "comment"
        case terminus = "terminus"
    }
    public var category: Category?
    public var type: String?
    public var value: String?
    public var commentType: String?
    public var id: String?


    public init() {}
    required public init?(map: Map) {

    }


    enum CodingKeys: String, CodingKey {
        case category = "category"
        case type = "type"
        case value = "value"
        case commentType = "comment_type"
        case id = "id"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(category, forKey: .category)
        try container.encode(type, forKey: .type)
        try container.encode(value, forKey: .value)
        try container.encode(commentType, forKey: .commentType)
        try container.encode(id, forKey: .id)
    }

    public func mapping(map: Map) {
        category <- map["category"]
        type <- map["type"]
        value <- map["value"]
        commentType <- map["comment_type"]
        id <- map["id"]
    }

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["category"] = self.category?.rawValue
        nillableDictionary["type"] = self.type
        nillableDictionary["value"] = self.value
        nillableDictionary["comment_type"] = self.commentType
        nillableDictionary["id"] = self.id

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
