//
// RouteDisplayInformation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

open class RouteDisplayInformation: JSONEncodable, Mappable {

    public var direction: String?
    public var code: String?
    public var network: String?
    public var links: [LinkSchema]?
    public var color: String?
    public var label: String?
    public var commercialMode: String?
    public var textColor: String?
    public var name: String?

    public init() {}
    required public init?(map: Map) {

    }


    public func mapping(map: Map) {
        direction <- map["direction"]
        code <- map["code"]
        network <- map["network"]
        links <- map["links"]
        color <- map["color"]
        label <- map["label"]
        commercialMode <- map["commercial_mode"]
        textColor <- map["text_color"]
        name <- map["name"]
    }

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["direction"] = self.direction
        nillableDictionary["code"] = self.code
        nillableDictionary["network"] = self.network
        nillableDictionary["links"] = self.links?.encodeToJSON()
        nillableDictionary["color"] = self.color
        nillableDictionary["label"] = self.label
        nillableDictionary["commercial_mode"] = self.commercialMode
        nillableDictionary["text_color"] = self.textColor
        nillableDictionary["name"] = self.name

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
