//
// Severity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Severity: JSONEncodable, Mappable, Codable {

    public enum Effect: String, Codable { 
        case noService = "NO_SERVICE"
        case reducedService = "REDUCED_SERVICE"
        case significantDelays = "SIGNIFICANT_DELAYS"
        case detour = "DETOUR"
        case additionalService = "ADDITIONAL_SERVICE"
        case modifiedService = "MODIFIED_SERVICE"
        case otherEffect = "OTHER_EFFECT"
        case unknownEffect = "UNKNOWN_EFFECT"
        case stopMoved = "STOP_MOVED"
    }
    public var color: String?
    public var priority: Int32?
    public var name: String?
    public var effect: Effect?


    public init() {}
    required public init?(map: Map) {

    }


    enum CodingKeys: String, CodingKey {
        case color = "color"
        case priority = "priority"
        case name = "name"
        case effect = "effect"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(color, forKey: .color)
        try container.encode(priority, forKey: .priority)
        try container.encode(name, forKey: .name)
        try container.encode(effect, forKey: .effect)
    }

    public func mapping(map: Map) {
        color <- map["color"]
        priority <- map["priority"]
        name <- map["name"]
        effect <- map["effect"]
    }

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["color"] = self.color
        nillableDictionary["priority"] = self.priority?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["effect"] = self.effect?.rawValue

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
