//
// ValidityPattern.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class ValidityPattern: JSONEncodable, Mappable, Codable {

    public var beginningDate: String?
    public var days: String?

    public init() {}
    required public init?(map: Map) {

    }


    enum CodingKeys: String, CodingKey {
        case beginningDate = "beginning_date"
        case days = "days"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(beginningDate, forKey: .beginningDate)
        try container.encode(days, forKey: .days)
    }

    public func mapping(map: Map) {
        beginningDate <- map["beginning_date"]
        days <- map["days"]
    }

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["beginning_date"] = self.beginningDate
        nillableDictionary["days"] = self.days

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
